# -*- coding: utf-8 -*-
"""Treści podstron SEO — część 2: typy wydarzeń, eventy branżowe, imprezy prywatne."""

from seo_pages_content_helpers import ev, br, priv, chain_related

# ================================================= TYPY WYDARZEŃ (biznes)

EVENTS = [
    ev("robot-na-event", "Robot na event", "na event", "Na evencie",
       sub="Jedna atrakcja, która działa na każdym wydarzeniu: robot humanoidalny Unitree G1 wita gości, tańczy, rozmawia dzięki AI i pozuje do zdjęć. Cokolwiek organizujesz — robot zamienia to w event, o którym się mówi.",
       uniq_tile=("Uniwersalność", "Działa na każdym wydarzeniu", "Targi, gala, piknik czy premiera — scenariusz pokazu dopasowujemy do charakteru i agendy Twojego eventu. Jeden robot, dziesiątki sprawdzonych wariantów."),
       uniq_scen=("Program szyty na miarę", "Przed wydarzeniem ustalamy wspólnie plan: kiedy robot wchodzi, co pokazuje, z kim wchodzi w interakcje. Dostajesz scenariusz minuta po minucie — i pewność, że wszystko zagra."),
       faq_uniq=("Na jakie eventy najczęściej wynajmowany jest robot?", "Najczęściej obsługujemy targi, konferencje, gale i imprezy firmowe, ale robot świetnie sprawdza się też na weselach, festynach czy otwarciach. Jeśli masz nietypowe wydarzenie — napisz, na pewno coś wymyślimy."),
       video="taniec", guides="cena"),
    ev("robot-na-targi", "Robot na targi", "na targi", "Na targach",
       sub="Na targach masz 3 sekundy, żeby zatrzymać przechodzącego. Robot humanoidalny przy stoisku robi to za Ciebie — buduje tłum, zbiera kontakty i sprawia, że to o Twoim stoisku mówi cała hala.",
       uniq_tile=("Leady", "Tłum, który zostawia kontakty", "Robot przyciąga odwiedzających, a Twoi handlowcy rozmawiają z ludźmi, którzy sami podeszli. Skaner kodów nie nadąża — to najlepszy problem, jaki można mieć na targach."),
       uniq_scen=("Praca przy stoisku", "Robot pracuje przed Twoim stoiskiem w blokach: pokazy choreografii przyciągają falę odwiedzających, a między nimi G1 wita gości i pozuje do zdjęć na tle Twojego brandingu."),
       faq_uniq=("Czy robot zmieści się na naszym stoisku?", "G1 potrzebuje zaledwie kilku metrów kwadratowych wolnej przestrzeni. Pracujemy zarówno na dużych stoiskach wyspowych, jak i przy zabudowie szeregowej — układ ustalamy na podstawie projektu stoiska."),
       video="spacer", guides="targi",
       blog=("blog-robot-na-stoisko-targowe.html", "robot na stoisku targowym — jak zebrać leady"),
       related=[("oferta-targi.html", "Oferta targowa"), ("robot-na-expo.html", "Robot na expo")]),
    ev("robot-na-konferencje", "Robot na konferencję", "na konferencję", "Na konferencji",
       sub="Konferencja zapamiętana to konferencja udana. Robot humanoidalny otwiera wydarzenie, współprowadzi agendę albo występuje jako prelegent — i daje uczestnikom powód, by mówić o Twoim wydarzeniu długo po jego zakończeniu.",
       uniq_tile=("Agenda", "Punkt programu, nie dekoracja", "Robot może otworzyć konferencję, zapowiadać prelegentów albo wygłosić własne wystąpienie z sesją Q&A. To pełnoprawny element agendy, który podnosi rangę całego wydarzenia."),
       uniq_scen=("Otwarcie konferencji", "Robot wchodzi na scenę o własnych siłach i wita uczestników — otwarcie, po którym frekwencja na sali utrzymuje się do ostatniego slotu."),
       faq_uniq=("Czy robot może wystąpić jako prelegent?", "Tak — G1 może wygłosić przygotowane wspólnie wystąpienie i odpowiadać na pytania sali dzięki AI. Zobacz naszą stronę o robocie prelegencie."),
       video="gesty", guides="ai",
       blog=("blog-robot-targi-vs-konferencja.html", "robot na targach vs na konferencji"),
       related=[("oferta-konferencje.html", "Oferta konferencyjna"), ("robot-prelegent.html", "Robot prelegent")]),
    ev("robot-na-konferencje-technologiczna", "Robot na konferencję technologiczną", "na konferencję technologiczną", "Na konferencji technologicznej",
       sub="Publiczność techniczna widziała już wszystko — poza chodzącym humanoidem na żywo. Robot na konferencji technologicznej to spójny z tematyką highlight, który nawet najbardziej wymagającą publiczność zamienia w nagrywających fanów.",
       uniq_tile=("Merytoryka", "Technologia, nie gadżet", "Dla publiczności tech robot to nie tylko show — to demonstracja stanu robotyki i AI. Pokaz można połączyć z omówieniem technologii lokomocji i integracji z modelami językowymi."),
       uniq_scen=("Demo na scenie głównej", "Pokaz możliwości G1 z komentarzem technicznym: lokomocja dwunożna, balans, AI. Publiczność inżynierska docenia szczegóły — i nagrywa wszystko."),
       faq_uniq=("Czy pokaz może mieć charakter techniczny?", "Tak — dla wydarzeń technologicznych przygotowujemy wariant pokazu z merytorycznym komentarzem o robotyce i AI, dostosowanym do poziomu publiczności."),
       video="spacer", guides="ai"),
    ev("robot-na-gale", "Robot na galę", "na galę", "Na gali",
       sub="Gala to wieczór, który ma być pamiętany. Robot humanoidalny w eleganckim wydaniu: wita gości na czerwonym dywanie, wręcza statuetki i prowadzi pokaz finałowy. Klasa spotyka przyszłość.",
       uniq_tile=("Ceremonia", "Wręcza nagrody i wyróżnienia", "Statuetka wręczona przez robota to moment, który każdy laureat zapamięta — a fotografowie uwiecznią. Ceremonia zyskuje dramaturgię, o jakiej nie śniło się scenografom."),
       uniq_scen=("Czerwony dywan", "Robot wita gości u wejścia na galę — eleganckie powitanie, przy którym każdy zatrzymuje się na zdjęcie, zanim wejdzie na salę."),
       faq_uniq=("Czy robot może wręczać nagrody na gali?", "Tak — G1 może podawać statuetki, zapraszać laureatów na scenę i towarzyszyć ceremonii. To jeden z najbardziej efektownych scenariuszy galowych."),
       video="taniec",
       blog=("blog-atrakcja-na-gale-firmowa.html", "atrakcja na galę firmową — przewodnik"),
       related=[("oferta-konferencje.html", "Oferta: konferencje i gale"), ("robot-na-bankiet.html", "Robot na bankiet")]),
    ev("robot-na-bankiet", "Robot na bankiet", "na bankiet", "Na bankiecie",
       sub="Bankiet rządzi się swoimi prawami: eleganckie rozmowy, networking, kieliszek w dłoni. Robot humanoidalny krąży wśród gości jako temat, który łamie lody lepiej niż jakikolwiek small talk.",
       uniq_tile=("Networking", "Najlepszy icebreaker wieczoru", "Przy robocie nieznajomi zaczynają rozmawiać ze sobą naturalnie — wspólne zaskoczenie to najszybszy sposób na nawiązanie kontaktu. Networking dzieje się sam."),
       uniq_scen=("Krążenie wśród gości", "Robot w asyście operatora przechadza się między stolikami i strefami — wita, gestykuluje, pozuje. Wszędzie, gdzie się pojawi, wybucha rozmowa."),
       faq_uniq=("Czy robot pasuje do eleganckiego charakteru bankietu?", "Tak — pokaz prowadzimy w stonowanym, eleganckim stylu: spokojne interakcje, dyskretna obecność operatora i momenty show dokładnie tam, gdzie chce ich gospodarz wieczoru."),
       video="powitanie"),
    ev("robot-na-impreze-firmowa", "Robot na imprezę firmową", "na imprezę firmową", "Na imprezie firmowej",
       sub="Impreza firmowa, na którą pracownicy naprawdę chcą przyjść? Robot humanoidalny załatwia frekwencję, integrację i content na firmowe social media jednym pokazem. A dział HR zbiera gratulacje.",
       uniq_tile=("Integracja", "Wspólny temat dla wszystkich działów", "Księgowość, IT i sprzedaż — przy robocie wszyscy stoją w tym samym tłumie i śmieją się z tych samych momentów. Tak wygląda integracja bez wymuszania."),
       uniq_scen=("Punkt kulminacyjny wieczoru", "Pokaz choreografii w środku imprezy resetuje energię i daje wieczorowi moment, do którego wszyscy będą wracać w poniedziałkowych rozmowach."),
       faq_uniq=("Czy robot sprawdzi się i na eleganckiej gali, i na luźnej imprezie?", "Tak — charakter pokazu dopasowujemy do wydarzenia: od eleganckiego programu galowego po energetyczne show z bitwą taneczną na luźnej imprezie zespołowej."),
       video="taniec",
       blog=("blog-atrakcja-na-event-firmowy.html", "atrakcja na event firmowy — przewodnik")),
    ev("roboty-na-eventy-firmowe", "Roboty na eventy firmowe", "na eventy firmowe", "Na evencie firmowym",
       sub="Od pikniku rodzinnego po galę zarządu: roboty humanoidalne obsługują pełne spektrum wydarzeń firmowych. Sprawdzony partner do eventów, który zawsze dowozi efekt WOW — i materiał do firmowej komunikacji.",
       uniq_tile=("Kalendarz", "Partner na cały rok eventowy", "Wigilia, kick-off, piknik, jubileusz — przy współpracy cyklicznej robot pojawia się na kolejnych wydarzeniach firmy w coraz to nowych rolach. Pracownicy czekają, co wymyślimy tym razem."),
       uniq_scen=("Format pod każdy typ wydarzenia", "Dla każdego eventu w firmowym kalendarzu mamy scenariusz: powitania na konferencji, taniec na imprezie, pokazy dla rodzin na pikniku. Jedna współpraca, wiele odsłon."),
       faq_uniq=("Czy przy kilku eventach w roku można liczyć na lepsze warunki?", "Tak — dla firm planujących kilka wydarzeń w roku przygotowujemy ofertę ramową z preferencyjnymi stawkami i gwarancją terminów."),
       video="gesty", guides="marketing"),
    ev("robot-na-integracje-firmowa", "Robot na integrację firmową", "na integrację firmową", "Na integracji",
       sub="Zamiast kolejnego paintballa — spotkanie z prawdziwym robotem. Na integracji firmowej G1 daje zespołowi wspólne przeżycie, bitwę taneczną i setki zdjęć, które będą krążyć po firmowych czatach miesiącami.",
       uniq_tile=("Zespół", "Przeżycie, które łączy", "Wspólne zaskoczenie integruje szybciej niż wymuszone gry zespołowe. Robot daje każdemu — od stażysty po prezesa — ten sam powód do śmiechu."),
       uniq_scen=("Bitwa taneczna zespołów", "Działy wystawiają swoich reprezentantów do tanecznego pojedynku z robotem — doping, śmiech i nagrania, które zobaczy cała firma."),
       faq_uniq=("Czy robot sprawdzi się na integracji w plenerze?", "Tak — przy suchej pogodzie i w miarę równej nawierzchni robot świetnie pracuje na zewnątrz. Na wypadek deszczu ustalamy wariant pod dachem."),
       video="taniec"),
    ev("robot-na-piknik-firmowy", "Robot na piknik firmowy", "na piknik firmowy", "Na pikniku firmowym",
       sub="Piknik firmowy to event dla pracowników i ich rodzin — a robot humanoidalny to jedyna atrakcja, która działa równie mocno na pięciolatka, jak na prezesa. Pokazy, wspólne tańce i piątki z robotem przez całe popołudnie.",
       uniq_tile=("Rodziny", "Hit wśród dzieci pracowników", "Dzieci wracają z pikniku z opowieścią o prawdziwym robocie — a pracownicy z poczuciem, że firma zorganizowała coś naprawdę wyjątkowego. Tak buduje się lojalność."),
       uniq_scen=("Bloki pokazowe przez cały piknik", "Robot pracuje w rytmie pikniku: pokazy co godzinę, między nimi strefa zdjęć i interakcji. Każda rodzina znajdzie swój moment z robotem."),
       faq_uniq=("Czy robot może występować na trawie?", "Robot najlepiej pracuje na utwardzonej, równej nawierzchni — na piknikach wyznaczamy strefę pokazów na podeście, kostce lub płycie. Doradzimy, jak to zorganizować."),
       video="gesty", guides="dzieci",
       blog=("blog-robot-na-piknik-firmowy.html", "robot na pikniku firmowym — poradnik")),
    ev("robot-na-team-building", "Robot na team building", "na team building", "Na spotkaniu teambuildingowym",
       sub="Team building z robotem humanoidalnym to nie warsztat z flipchartem. Zespół wspólnie odkrywa możliwości G1, rywalizuje w wyzwaniach z robotem i wychodzi z przeżyciem, które naprawdę zbliża.",
       uniq_tile=("Aktywność", "Wyzwania zespołowe z robotem", "Konkursy taneczne, quizy z AI, wyzwania na refleks — program teambuildingowy budujemy wokół interakcji z robotem, w których liczy się współpraca, nie indywidualne popisy."),
       uniq_scen=("Warsztat z przyszłością", "Część pokazową łączymy z rozmową o AI i robotyce w pracy — zespół nie tylko się bawi, ale też dotyka technologii, o której wszyscy dyskutują."),
       faq_uniq=("Ilu osobowe grupy obsługujecie na team buildingu?", "Od kameralnych zespołów kilkunastoosobowych po całe działy liczące setki osób — program skalujemy do wielkości grupy i przestrzeni."),
       video="gesty"),
    ev("robot-na-szkolenie", "Robot na szkolenie", "na szkolenie", "Na szkoleniu",
       sub="Najtrudniejszy moment każdego szkolenia? Utrzymanie uwagi po lunchu. Robot humanoidalny jako przerywnik lub motyw przewodni szkolenia podnosi energię sali i sprawia, że przekaz zostaje w głowach.",
       uniq_tile=("Uwaga", "Energia sali pod kontrolą", "Krótki pokaz robota między blokami szkolenia działa jak restart — uczestnicy wracają do treści z nową energią i pozytywnym nastawieniem."),
       uniq_scen=("Moduł o AI i przyszłości pracy", "Przy szkoleniach o transformacji cyfrowej robot staje się żywym case study — uczestnicy rozmawiają z AI zamiast oglądać slajdy o niej."),
       faq_uniq=("Czy robot pasuje do poważnej tematyki szkolenia?", "Tak — obecność robota dozujemy tak, by wspierała program, nie rozpraszała. Od krótkiego akcentu na otwarcie po pełny moduł interaktywny."),
       video="gesty", guides="ai"),
    ev("robot-na-rocznice-firmy", "Robot na rocznicę firmy", "na rocznicę firmy", "Na jubileuszu",
       sub="Jubileusz firmy patrzy w dwie strony: na dorobek i na przyszłość. Robot humanoidalny na rocznicy symbolicznie spina jedno z drugim — a przy okazji daje gościom wieczór, o którym będą opowiadać przy kolejnym jubileuszu.",
       uniq_tile=("Symbol", "Przyszłość na urodzinach firmy", "Humanoid na jubileuszu to czytelny komunikat dla pracowników i partnerów: ta firma nie świętuje przeszłości — buduje kolejną dekadę."),
       uniq_scen=("Toast i tort z robotem", "Robot może wznieść toast za firmę, odsłonić tort jubileuszowy albo wręczyć wyróżnienia zasłużonym pracownikom — ceremonia zyskuje moment, który przejdzie do firmowej legendy."),
       faq_uniq=("Czy robot może nawiązać do historii naszej firmy?", "Tak — dzięki AI robot może opowiedzieć o kamieniach milowych firmy, przywołać anegdoty i wywołać wspomnienia. Treść przygotowujemy wspólnie przed wydarzeniem."),
       video="powitanie"),
    ev("robot-na-premiere-produktu", "Robot na premierę produktu", "na premierę produktu", "Na premierze",
       sub="Premiera produktu potrzebuje momentu, w którym sala wstrzymuje oddech. Robot humanoidalny odsłania nowość, prezentuje ją i pozuje z nią do zdjęć — a media dostają obrazek, który chcą publikować.",
       uniq_tile=("Odsłonięcie", "Moment premiery z dramaturgią", "To robot ściąga zasłonę, wnosi produkt na scenę albo uruchamia go pierwszy raz publicznie. Fotografowie mają gotowy kadr, dziennikarze gotowy lead."),
       uniq_scen=("Prezentacja nowości", "Po odsłonięciu robot prezentuje kluczowe cechy produktu — przygotowanym skryptem, z gestykulacją — i odpowiada na pytania dzięki AI."),
       faq_uniq=("Czy robot może trzymać i prezentować nasz produkt?", "W zależności od gabarytów — G1 może trzymać lżejsze przedmioty, wskazywać na produkt i z nim pozować. Szczegóły ustalamy po poznaniu produktu."),
       video="branding", guides="marketing",
       blog=("blog-robot-na-premiere-produktu.html", "robot na premierze produktu — poradnik")),
    ev("robot-na-otwarcie", "Robot na otwarcie", "na otwarcie", "Na otwarciu",
       sub="Otwarcie sklepu, biura, salonu czy restauracji ma jeden cel: żeby okolica dowiedziała się o Was od razu. Robot humanoidalny przecina wstęgę, wita pierwszych gości i sprawia, że dzień otwarcia trafia do lokalnych mediów.",
       uniq_tile=("Rozgłos", "Lokalne media same przychodzą", "Otwarcie z robotem to gotowy temat dla lokalnych portali i telewizji — a każdy przechodzień z telefonem staje się Twoim kanałem promocji."),
       uniq_scen=("Ceremonia otwarcia", "Robot uczestniczy w przecięciu wstęgi, wita pierwszych klientów i prowadzi pokaz przed wejściem — trudno o mocniejszy sygnał, że w okolicy pojawiło się nowe miejsce."),
       faq_uniq=("Jak wcześnie planować robota na otwarcie?", "Termin otwarcia zwykle znamy z wyprzedzeniem — zarezerwuj robota 3–4 tygodnie wcześniej, a my pomożemy też zaplanować komunikację zapowiadającą atrakcję."),
       video="powitanie", guides="marketing",
       blog=("blog-robot-na-otwarcie-sklepu.html", "robot na otwarciu sklepu — case i poradnik")),
    ev("robot-na-dzien-otwarty", "Robot na dzień otwarty", "na dzień otwarty", "Na dniu otwartym",
       sub="Dzień otwarty jest po to, by ludzie przyszli — i wyszli z dobrym wrażeniem. Robot humanoidalny załatwia obie rzeczy: przyciąga odwiedzających zapowiedzią, a na miejscu zamienia zwiedzanie w wydarzenie.",
       uniq_tile=("Frekwencja", "Zapowiedź, która ściąga ludzi", "Informacja o pokazie robota w komunikacji przed wydarzeniem realnie podnosi frekwencję — ludzie przychodzą dla robota, a zostają dla Waszej oferty."),
       uniq_scen=("Przewodnik po przestrzeni", "Robot wita odwiedzających i zaprasza do kolejnych stref — zwiedzanie showroomu czy zakładu zyskuje narrację i rytm."),
       faq_uniq=("Czy robot może opowiadać o naszej ofercie?", "Tak — zasilamy AI wiedzą o Waszej firmie, a robot odpowiada na pytania odwiedzających o produkty, usługi czy rekrutację."),
       video="powitanie",
       related=[("oferta-dni-otwarte.html", "Oferta: dni otwarte"), ("robot-na-otwarcie.html", "Robot na otwarcie")]),
    ev("robot-na-targi-pracy", "Robot na targi pracy", "na targi pracy", "Na targach pracy",
       sub="Na targach pracy wszyscy rekruterzy mówią to samo. Robot humanoidalny przy Twoim stoisku mówi za Ciebie — i to tak, że kandydaci sami ustawiają się w kolejce, by porozmawiać o pracy w Twojej firmie.",
       uniq_tile=("Kandydaci", "CV zbierają się same", "Ruch przy stoisku z robotem jest kilkukrotnie większy niż u sąsiadów — rekruterzy rozmawiają z kandydatami, którzy przyszli z ciekawości i zostali z zainteresowania."),
       uniq_scen=("Robot w zespole rekrutacji", "G1 wita kandydatów, opowiada o firmie dzięki AI i zaprasza do rozmowy z rekruterem — pierwszy kontakt z marką pracodawcy, którego nie zapewni żaden roll-up."),
       faq_uniq=("Co robot może opowiedzieć kandydatom?", "Wszystko, co ustalimy: o kulturze firmy, benefitach, otwartych stanowiskach i procesie rekrutacji. Treści przygotowujemy wspólnie z Waszym HR."),
       video="powitanie", guides="marketing",
       blog=("blog-robot-na-targi-pracy.html", "robot na targach pracy — jak przyciągnąć kandydatów"),
       related=[("robot-employer-branding.html", "Robot w employer brandingu"), ("robot-na-targi.html", "Robot na targi")]),
    ev("robot-na-roadshow", "Robot na roadshow", "na roadshow", "Na roadshow",
       sub="Roadshow żyje z powtarzalnego efektu w każdym mieście trasy. Robot humanoidalny to atrakcja, która w Gdańsku działa tak samo mocno jak w Rzeszowie — a logistykę bierzemy na siebie.",
       uniq_tile=("Trasa", "Cała Polska w jednym projekcie", "Planujemy obecność robota na całej trasie: terminy, transport, ten sam zespół i standard pokazu w każdym mieście. Ty dostajesz jeden kontakt i zero niespodzianek."),
       uniq_scen=("Ten sam scenariusz, nowe miasto", "W każdej lokalizacji robot odtwarza sprawdzony program: pokazy, interakcje, strefa zdjęć z brandingiem. Spójność, którą doceni każdy brand manager."),
       faq_uniq=("Jak rozliczana jest trasa wielomiastowa?", "Przy roadshow przygotowujemy wycenę pakietową na całą trasę — korzystniejszą niż suma pojedynczych realizacji. Napisz z planowaną listą miast."),
       video="branding", guides="marketing"),
    ev("robot-na-wystawe", "Robot na wystawę", "na wystawę", "Na wystawie",
       sub="Wystawa przyciąga zwiedzających eksponatami — ale to eksponat, który chodzi i rozmawia, zbiera największe tłumy. Robot humanoidalny na wystawie to żywa instalacja, która nie potrzebuje gabloty.",
       uniq_tile=("Ekspozycja", "Eksponat, który odpowiada na pytania", "Zwiedzający mogą z robotem porozmawiać — o wystawie, o technologii, o czymkolwiek. Żaden inny eksponat nie daje takiego doświadczenia."),
       uniq_scen=("Żywa instalacja", "Robot pracuje w wyznaczonej strefie wystawy w blokach pokazowych — zwiedzający planują wizytę pod godziny jego występów."),
       faq_uniq=("Czy robot może być częścią ekspozycji przez wiele dni?", "Tak — realizujemy zarówno pojedyncze dni, jak i dłuższe obecności z ustalonym harmonogramem bloków pokazowych."),
       video="spacer"),
    ev("robot-na-expo", "Robot na expo", "na expo", "Na expo",
       sub="Na wielkich wydarzeniach expo konkurujesz o uwagę z setkami wystawców. Robot humanoidalny to najkrótsza droga, by Twoja przestrzeń stała się punktem, do którego zmierzają wszyscy zwiedzający.",
       uniq_tile=("Skala", "Widoczność w wielkiej hali", "Na expo wygrywa ten, o kim mówi się w kuluarach. Chodzący humanoid generuje szum, który prowadzi zwiedzających prosto do Twojej ekspozycji."),
       uniq_scen=("Magnes na zwiedzających", "Robot pracuje przy Twojej przestrzeni w cyklicznych blokach — każdy pokaz buduje falę odwiedzin, którą zagospodarowuje Twój zespół."),
       faq_uniq=("Czy obsługujecie wydarzenia międzynarodowe?", "Tak — robot prowadzi interakcje także po angielsku, co na międzynarodowych expo jest ogromnym atutem."),
       video="spacer", guides="targi"),
    ev("robot-na-konwent", "Robot na konwent", "na konwent", "Na konwencie",
       sub="Konwent — branżowy, franczyzowy czy fanowski — potrzebuje momentów, które łączą uczestników. Robot humanoidalny daje wspólne przeżycie setkom osób naraz i staje się nieoficjalnym symbolem całego zjazdu.",
       uniq_tile=("Zjazd", "Temat numer jeden w kuluarach", "Od rejestracji po bankiet — robot przewija się przez cały konwent i staje się wspólnym punktem odniesienia wszystkich uczestników."),
       uniq_scen=("Obecność przez cały konwent", "Robot pojawia się w kluczowych momentach: otwarcie, przerwy networkingowe, gala wieczorna. Uczestnicy szukają go między punktami agendy."),
       faq_uniq=("Czy robot sprawdzi się na konwencie fanowskim?", "Zdecydowanie — publiczność popkulturowa reaguje na humanoida entuzjastycznie. Robot może nawiązywać do motywu przewodniego konwentu."),
       video="gesty"),
    ev("robot-na-festiwal", "Robot na festiwal", "na festiwal", "Na festiwalu",
       sub="Festiwal to tysiące ludzi szukających przeżyć. Robot humanoidalny w strefie festiwalowej przyciąga tłumy między koncertami i daje sponsorom aktywację, którą uczestnicy naprawdę lubią.",
       uniq_tile=("Strefa", "Aktywacja, która nie wkurza", "Uczestnicy festiwali omijają nachalne stoiska — ale do robota ustawiają się sami. To aktywacja sponsorska, którą ludzie wspominają dobrze."),
       uniq_scen=("Strefa robota między scenami", "W przerwach między występami robot prowadzi pokazy i interakcje — zagospodarowuje czas, w którym uczestnicy szukają atrakcji."),
       faq_uniq=("Czy robot pracuje na festiwalach plenerowych?", "Tak — przy zadaszonej strefie lub dobrej pogodzie robot świetnie pracuje w plenerze. Wymagamy równej nawierzchni; szczegóły w riderze."),
       video="taniec",
       blog=("blog-robot-na-juwenalia-festiwal.html", "robot na juwenaliach i festiwalach")),
    ev("robot-na-dni-miasta", "Robot na dni miasta", "na dni miasta", "Na dniach miasta",
       sub="Dni miasta gromadzą całe rodziny — i to właśnie dla nich robot humanoidalny jest atrakcją numer jeden. Pokazy na scenie, spacery wśród mieszkańców i tłumy przy strefie zdjęć: miasto będzie o tym mówić do przyszłego roku.",
       uniq_tile=("Mieszkańcy", "Atrakcja dla każdego pokolenia", "Od przedszkolaków po seniorów — robot działa na wszystkich mieszkańców jednakowo. To rzadkość w programach imprez miejskich."),
       uniq_scen=("Pokazy na scenie miejskiej", "Występy robota wplatamy w program sceniczny dni miasta — między koncertami a konkursami, z zapowiedzią konferansjera."),
       faq_uniq=("Czy współpracujecie z samorządami?", "Tak — obsługujemy wydarzenia miejskie i gminne, wystawiamy faktury dla jednostek publicznych i dostosowujemy się do procedur zamówień."),
       video="taniec"),
    ev("robot-na-wystep-sceniczny", "Robot na występ sceniczny", "na występ sceniczny", "Na scenie",
       sub="Scena to naturalne środowisko G1. Występ sceniczny robota — solo albo w duecie z artystą, tancerzem czy prowadzącym — to kilkuminutowe widowisko, po którym publiczność wstaje z miejsc.",
       uniq_tile=("Widowisko", "Reżyseria i światło", "Współpracujemy z realizatorami światła i dźwięku, by występ robota był pełnoprawnym numerem scenicznym — z dramaturgią, nie tylko efektem nowości."),
       uniq_scen=("Duet z artystą", "Robot występuje z wokalistą, tancerzem lub iluzjonistą — kontrast człowieka i maszyny na scenie daje widowisko, które publiczność nagrywa od pierwszej sekundy."),
       faq_uniq=("Czego potrzebuje robot na scenie?", "Równej, stabilnej sceny, kilku metrów przestrzeni i chwili na próbę techniczną. Pełny rider techniczny wysyłamy po rezerwacji terminu."),
       video="taniec",
       related=[("show-robotow.html", "Show robotów"), ("robot-tancerz.html", "Robot tancerz")]),
    ev("robot-na-ceremonie", "Robot na ceremonię", "na ceremonię", "Podczas ceremonii",
       sub="Wmurowanie kamienia węgielnego, wodowanie, wręczenie certyfikatów, jubileuszowa akademia — każda ceremonia zyskuje rangę, gdy bierze w niej udział robot humanoidalny. Powaga i przyszłość w jednym kadrze.",
       uniq_tile=("Ranga", "Ceremonia, którą się pamięta", "Udział robota podnosi rangę uroczystości i przyciąga media — moment ceremonialny zyskuje oprawę, której nie da się skopiować."),
       uniq_scen=("Udział w rytuale", "Robot może wręczać, odsłaniać, przecinać i podawać — każdy gest ceremonii ćwiczymy wcześniej, by przebiegł idealnie."),
       faq_uniq=("Czy robot zachowa powagę uroczystości?", "Tak — scenariusz ceremonii prowadzimy w tonie, jakiego wymaga chwila. Robot potrafi być widowiskowy bez naruszania powagi wydarzenia."),
       video="powitanie"),
]

# ============================================== EVENTY BRANŻOWE

BRANZE = [
    br("it", "event IT", "na event IT", "Na evencie IT",
       aud="deweloperów, inżynierów i CTO",
       uniq="Publiczność IT docenia robota podwójnie: jako świetne show i jako realne demo stanu robotyki oraz AI — z pytaniami o stack technologiczny włącznie.",
       faq=("Czy robot zainteresuje doświadczonych inżynierów?", "Tak — to właśnie publiczność techniczna zadaje najciekawsze pytania i najdłużej zostaje przy robocie. Na życzenie pokaz prowadzi operator gotowy na techniczne Q&A.")),
    br("gamingowy", "event gamingowy", "na event gamingowy", "Na evencie gamingowym",
       aud="graczy, streamerów i twórców",
       uniq="Społeczność gamingowa żyje contentem — a robot humanoidalny to gotowy materiał na klipy, streamy i shorty. G1 może wystąpić w motywach nawiązujących do gier i e-sportu.",
       faq=("Czy robot może pojawić się na streamie?", "Tak — robot świetnie wypada na żywo w transmisjach. Chętnie zgramy jego obecność z harmonogramem streamów i aktywności twórców na Twoim evencie.")),
    br("korporacyjny", "event korporacyjny", "na event korporacyjny", "Na evencie korporacyjnym",
       aud="pracowników, zarząd i partnerów biznesowych",
       uniq="W korporacyjnym kalendarzu robot odnajduje się wszędzie: od townhallu, przez kick-off sprzedażowy, po spotkanie z kluczowymi klientami — zawsze w tonie dopasowanym do rangi spotkania.",
       faq=("Czy pokaz można dopasować do wytycznych korporacyjnych?", "Tak — pracujemy z brand bookami, działami compliance i agendami co do minuty. Scenariusz zatwierdzasz przed wydarzeniem.")),
    br("medyczny", "event medyczny", "na event medyczny", "Na evencie medycznym",
       aud="lekarzy, farmaceutów i menedżerów ochrony zdrowia",
       uniq="Konferencje medyczne mówią o przyszłości leczenia — robot humanoidalny czyni tę przyszłość namacalną i otwiera rozmowy o technologii w medycynie lepiej niż niejeden wykład.",
       faq=("Czy robot pasuje do powagi wydarzenia medycznego?", "Tak — na wydarzeniach medycznych prowadzimy pokaz w stonowanym, profesjonalnym tonie, z akcentem na technologię i jej zastosowania, nie na rozrywkę.")),
    br("farmaceutyczny", "event farmaceutyczny", "na event farmaceutyczny", "Na evencie farmaceutycznym",
       aud="przedstawicieli branży farmaceutycznej",
       uniq="Cykliczne zjazdy i konferencje farmaceutyczne bywają do siebie podobne — robot humanoidalny wyróżnia Twoje wydarzenie i daje uczestnikom temat, który przetrwa do kolejnej edycji.",
       faq=("Czy robot może wspierać przekaz naukowy wydarzenia?", "Tak — treści, które robot przekazuje dzięki AI, przygotowujemy wspólnie z organizatorem, także w oparciu o materiały merytoryczne wydarzenia.")),
    br("finansowy", "event finansowy", "na event finansowy", "Na evencie finansowym",
       aud="bankowców, inwestorów i przedstawicieli fintechów",
       uniq="Branża finansowa mówi o AI na każdej konferencji — robot humanoidalny pozwala gościom tej AI dosłownie uścisnąć dłoń. Mocny akcent na galach wyników i kongresach fintech.",
       faq=("Czy robot sprawdzi się na eleganckim wydarzeniu finansowym?", "Tak — od powitania gości w strefie VIP po wystąpienie o przyszłości finansów: scenariusz utrzymujemy w tonie premium, spójnym z powagą branży.")),
    br("prawniczy", "event prawniczy", "na event prawniczy", "Na evencie prawniczym",
       aud="prawników, radców i przedstawicieli kancelarii",
       uniq="Legal tech to najgorętszy temat branży — a robot z AI na evencie prawniczym zamienia dyskusję o przyszłości zawodu w doświadczenie, które uczestnicy zapamiętają z konkretnej kancelarii czy konferencji.",
       faq=("O czym robot może mówić na wydarzeniu prawniczym?", "Np. o AI w pracy prawnika, automatyzacji i przyszłości usług prawnych — treść przygotowujemy wspólnie, z humorem wyważonym pod publiczność.")),
    br("nieruchomosci", "event branży nieruchomości", "na event branży nieruchomości", "Na evencie nieruchomościowym",
       aud="deweloperów, pośredników i inwestorów",
       uniq="Na targach mieszkaniowych i premierach inwestycji robot przyciąga klientów do stoiska dewelopera — a prezentację inwestycji zamienia w wydarzenie, o którym mówią kupujący.",
       faq=("Czy robot może pracować w biurze sprzedaży inwestycji?", "Tak — robot świetnie sprawdza się na otwarciach biur sprzedaży i dniach otwartych inwestycji, gdzie przyciąga rodziny oglądające mieszkania.")),
    br("budowlany", "event budowlany", "na event budowlany", "Na evencie budowlanym",
       aud="wykonawców, producentów i inżynierów budownictwa",
       uniq="Branża budowlana ceni konkret — i robot dostarcza konkret: technologię, którą widać, słychać i można przetestować. Na targach budowlanych stoisko z humanoidem zbiera największy ruch w hali.",
       faq=("Czy robot może pracować w hali targów budowlanych?", "Tak — typowe nawierzchnie hal targowych są dla robota idealne. Potrzebujemy tylko kilku metrów wolnej przestrzeni przy stoisku.")),
    br("przemyslowy", "event przemysłowy", "na event przemysłowy", "Na evencie przemysłowym",
       aud="inżynierów i menedżerów produkcji",
       uniq="Przemysł 4.0 i robotyzacja to tematy przewodnie branży — humanoid na evencie przemysłowym jest ich najlepszą ilustracją i naturalnym wstępem do rozmów o automatyzacji w Twojej ofercie.",
       faq=("Czy pokaz można połączyć z tematem automatyzacji?", "Tak — robot może otwierać dyskusję o robotyzacji produkcji, a operator opowiedzieć o realnych możliwościach współczesnych humanoidów.")),
    br("energetyczny", "event energetyczny", "na event energetyczny", "Na evencie energetycznym",
       aud="przedstawicieli sektora energii",
       uniq="Transformacja energetyczna to opowieść o przyszłości — robot humanoidalny nadaje tej opowieści twarz na kongresach, targach energetyki i galach sektora.",
       faq=("Czy robot wystąpi na kongresie branżowym z wieloma patronami?", "Tak — mamy doświadczenie w wydarzeniach z rozbudowaną strukturą partnerów; branding i rola robota są w pełni ustalane z organizatorem.")),
    br("logistyczny", "event logistyczny", "na event logistyczny", "Na evencie logistycznym",
       aud="menedżerów logistyki i łańcucha dostaw",
       uniq="Logistyka automatyzuje się szybciej niż jakakolwiek branża — robot humanoidalny na evencie logistycznym pokazuje kierunek tych zmian i przyciąga uczestników do stoisk oraz stref partnerów.",
       faq=("Czy robot może nawiązywać do automatyzacji magazynów?", "Tak — treści pokazu możemy osadzić w tematyce intralogistyki i automatyzacji, wspólnie z Waszym zespołem merytorycznym.")),
    br("motoryzacyjny", "event motoryzacyjny", "na event motoryzacyjny", "Na evencie motoryzacyjnym",
       aud="fanów motoryzacji i klientów salonów",
       uniq="Premiera modelu, otwarcie salonu, targi moto — robot obok samochodu to zestawienie, które przyciąga obiektywy. Technologiczny charakter humanoida idealnie gra z przekazem nowoczesnej motoryzacji.",
       faq=("Czy robot może uczestniczyć w premierze samochodu?", "Tak — robot może odsłonić auto, zaprezentować kluczowe cechy modelu i pozować z nim do zdjęć. To jeden z naszych ulubionych scenariuszy.")),
    br("telekomunikacyjny", "event telekomunikacyjny", "na event telekomunikacyjny", "Na evencie telco",
       aud="przedstawicieli branży telco i nowych technologii",
       uniq="Branża telco sprzedaje łączność i przyszłość — robot sterowany w czasie rzeczywistym jest efektowną demonstracją obu tych rzeczy na targach, konferencjach i eventach operatorów.",
       faq=("Czy robot może demonstrować możliwości sieci?", "Pokaz można narracyjnie powiązać z tematem łączności i niskich opóźnień — szczegóły scenariusza dopracowujemy z Waszym marketingiem.")),
    br("handlowy", "event handlowy", "na event handlowy", "Na evencie handlowym",
       aud="kupców, dystrybutorów i partnerów handlowych",
       uniq="Kongresy sieci, zjazdy partnerów i targi kontraktacyjne mają jeden cel: relacje. Robot humanoidalny daje uczestnikom wspólne przeżycie, które otwiera rozmowy handlowe lepiej niż jakikolwiek gadżet.",
       faq=("Czy robot może wspierać cele sprzedażowe wydarzenia?", "Tak — robot może zapraszać do stref ofertowych, wspierać premiery produktów i kierować uczestników do zespołu handlowego.")),
    br("gastronomiczny", "event gastronomiczny", "na event gastronomiczny", "Na evencie gastro",
       aud="szefów kuchni, restauratorów i foodies",
       uniq="Festiwale smaku i targi gastro żyją doznaniami — robot humanoidalny dodaje do nich doznanie technologiczne: wita gości, zapowiada pokazy kulinarne i pozuje ze smakołykami do zdjęć.",
       faq=("Czy robot może współprowadzić pokaz kulinarny?", "Tak — robot może zapowiadać szefów kuchni, komentować pokazy i angażować publiczność między degustacjami.")),
    br("turystyczny", "event turystyczny", "na event turystyczny", "Na evencie turystycznym",
       aud="branżę turystyczną i podróżników",
       uniq="Na targach turystycznych każde stoisko kusi plażą — Twoje może kusić spotkaniem z robotem. Humanoid zatrzymuje zwiedzających i daje obsłudze czas na rozmowę o ofercie wyjazdów.",
       faq=("Czy robot może mówić w językach obcych?", "Tak — poza polskim robot prowadzi interakcje po angielsku, co na międzynarodowych targach turystycznych jest dużym atutem.")),
    br("sportowy", "event sportowy", "na event sportowy", "Na evencie sportowym",
       aud="kibiców, zawodników i sponsorów",
       uniq="Mecz, turniej, gala sportu czy bieg masowy — robot humanoidalny rozgrzewa publiczność, prowadzi rozgrzewkę z kibicami i daje sponsorom aktywację, którą stadion nagradza brawami.",
       faq=("Czy robot może wystąpić w przerwie meczu?", "Tak — kilkuminutowy pokaz w przerwie to idealny format: dynamiczny, widowiskowy i gotowy na telebim.")),
    br("kulturalny", "event kulturalny", "na event kulturalny", "Na evencie kulturalnym",
       aud="publiczność festiwali i instytucji kultury",
       uniq="Sztuka spotyka technologię: robot humanoidalny na wernisażu, festiwalu czy w teatrze staje się performatywnym komentarzem do czasów — i frekwencyjnym magnesem dla instytucji.",
       faq=("Czy robot może wziąć udział w performansie artystycznym?", "Tak — współpracujemy z artystami i kuratorami; choreografię i rolę robota budujemy pod koncepcję artystyczną wydarzenia.")),
    br("modowy", "event modowy", "na event modowy", "Na evencie modowym",
       aud="projektantów, media modowe i gości pokazów",
       uniq="Robot na wybiegu albo w pierwszym rzędzie pokazu to obraz, który obiega media modowe. G1 może otworzyć pokaz, zaprezentować element kolekcji i wystąpić w sesjach okołopokazowych.",
       faq=("Czy robot może wystąpić w ubraniu lub akcesoriach?", "W ograniczonym zakresie tak — lekkie elementy stylizacji są możliwe. Szczegóły ustalamy z projektantem przed wydarzeniem.")),
    br("beauty", "event beauty", "na event beauty", "Na evencie beauty",
       aud="branżę kosmetyczną i beauty influencerów",
       uniq="Branża beauty żyje w social mediach — a nic nie generuje rolek tak, jak humanoid na premierze kosmetyku czy targach beauty. Robot wita gości, prezentuje nowości i pozuje do zdjęć z produktami.",
       faq=("Czy robot może prezentować produkty kosmetyczne?", "Tak — robot może trzymać i eksponować lekkie produkty, prezentować nowości i uczestniczyć w strefach foto z brandingiem marki.")),
    br("edukacyjny", "event edukacyjny", "na event edukacyjny", "Na evencie edukacyjnym",
       aud="uczniów, studentów i nauczycieli",
       uniq="Nie ma lepszej lekcji o przyszłości niż spotkanie z nią twarzą w twarz. Na piknikach naukowych, festiwalach edukacji i w szkołach robot zamienia abstrakcyjne pojęcia AI i robotyki w doświadczenie.",
       faq=("Czy pokaz ma wymiar edukacyjny?", "Tak — operator opowiada, jak robot chodzi, utrzymuje równowagę i rozumie mowę. Poziom opowieści dostosowujemy do wieku odbiorców."),
       guides="dzieci"),
    br("ekologiczny", "event ekologiczny", "na event ekologiczny", "Na evencie ekologicznym",
       aud="uczestników wydarzeń zrównoważonego rozwoju",
       uniq="Wydarzenia klimatyczne i ESG mówią o technologiach jutra — robot humanoidalny pokazuje je dziś. Elektryczny, cichy i wielokrotnego użytku: atrakcja spójna z przekazem zrównoważonego rozwoju.",
       faq=("Czy robot pasuje do przekazu ekologicznego wydarzenia?", "Tak — G1 jest w pełni elektryczny i cichy, a jego obecność dobrze współgra z narracją o odpowiedzialnych technologiach przyszłości.")),
    br("charytatywny", "event charytatywny", "na event charytatywny", "Na evencie charytatywnym",
       aud="darczyńców i gości aukcji",
       uniq="Na balu czy aukcji charytatywnej robot podnosi frekwencję i licytacje: może prowadzić zbiórkę, zapowiadać przedmioty aukcyjne i dziękować darczyńcom w sposób, którego nikt nie zapomni.",
       faq=("Czy oferujecie specjalne warunki dla fundacji?", "Tak — wydarzenia charytatywne traktujemy szczególnie. Napisz do nas z opisem inicjatywy, a przygotujemy indywidualną propozycję.")),
    br("startupowy", "event startupowy", "na event startupowy", "Na evencie startupowym",
       aud="founderów, inwestorów i społeczność startupową",
       uniq="Demo day, meetup czy konferencja startupowa: robot humanoidalny przyciąga inwestorów i media do Twojej sceny — a networkingowi daje temat otwierający każdą rozmowę.",
       faq=("Czy robot może wesprzeć pitch naszego startupu?", "Tak — robot może zapowiedzieć Twój pitch, wystąpić w demo albo przyciągać ruch do stoiska podczas targów startupowych.")),
    br("miejski", "event miejski", "na event miejski", "Na evencie miejskim",
       aud="mieszkańców i rodziny",
       uniq="Festyny, pikniki dzielnicowe i wydarzenia plenerowe miast zyskują z robotem atrakcję, która ściąga mieszkańców w każdym wieku — i pokazuje miasto jako otwarte na nowoczesność.",
       faq=("Czy realizujecie zamówienia publiczne?", "Tak — współpracujemy z samorządami i instytucjami miejskimi, wystawiamy faktury i dostosowujemy się do wymogów formalnych zamówień.")),
    br("outdoor", "event outdoor", "na event outdoor", "Na evencie plenerowym",
       aud="uczestników wydarzeń plenerowych",
       uniq="Robot humanoidalny pracuje także pod chmurką: pikniki, festyny i strefy plenerowe to jego naturalne środowisko, o ile zapewnimy mu równą nawierzchnię i suchą pogodę — resztą zajmujemy się my.",
       faq=("Jakie warunki musi spełniać teren plenerowy?", "Równa, utwardzona nawierzchnia (podest, kostka, asfalt) i osłona na wypadek deszczu. Wysyłamy prosty rider, który rozwiewa wszystkie wątpliwości."),
       blog=("blog-robot-na-event-plenerowy.html", "robot na evencie plenerowym — poradnik")),
    br("hybrydowy", "event hybrydowy", "na event hybrydowy", "Na evencie hybrydowym",
       aud="uczestników na sali i online",
       uniq="Event hybrydowy musi angażować dwie publiczności naraz — robot humanoidalny działa na obie: na sali buduje tłum, a w transmisji daje realizatorom najatrakcyjniejszy kadr całego wydarzenia.",
       faq=("Czy robot dobrze wypada w transmisji online?", "Świetnie — dynamiczne ujęcia robota podnoszą oglądalność streamu. Chętnie zgramy pokazy z reżyserką transmisji.")),
    br("vip", "event VIP", "na event VIP", "Na evencie VIP",
       aud="gości specjalnych i klientów premium",
       uniq="Kameralne wydarzenie dla wybranych gości wymaga atrakcji z najwyższej półki. Prywatny pokaz humanoida — z powitaniem imiennym i interakcjami szytymi na miarę — to doświadczenie zarezerwowane dla nielicznych.",
       faq=("Czy zapewniacie dyskrecję na zamkniętych wydarzeniach?", "Tak — obsługujemy wydarzenia objęte poufnością, podpisujemy NDA i nie publikujemy materiałów bez zgody organizatora."),
       video="powitanie"),
]

# ============================================ IMPREZY PRYWATNE

PRIVATE = [
    priv("robot-na-urodziny", "Robot na urodziny", "na urodziny", "Na urodzinach",
         sub="Urodziny z prawdziwym robotem — dla dziecka spełnienie marzeń, dla dorosłego impreza, o której będzie mówić całe towarzystwo. G1 tańczy, składa życzenia, przybija piątki i pozuje do zdjęć z solenizantem.",
         uniq_scen=("Życzenia od robota", "Robot składa solenizantowi życzenia głosem — imiennie, z humorem, do kamery. Ten moment zostaje w rodzinnym archiwum na zawsze."),
         faq_uniq=("Czy robot sprawdzi się na urodzinach dziecka i dorosłego?", "Tak — mamy warianty pokazu dla dzieci (zabawy, piątki, wspólny taniec) i dla dorosłych (show, życzenia, strefa foto). Powiedz nam, kto świętuje, a dobierzemy program.")),
    priv("robot-na-imieniny", "Robot na imieniny", "na imieniny", "Na imieninach",
         sub="Imieniny z niespodzianką, jakiej nie widziała rodzina: robot humanoidalny składa życzenia solenizantowi, tańczy z gośćmi i zamienia domowe przyjęcie w wydarzenie roku w całej rodzinie.",
         uniq_scen=("Niespodzianka dla solenizanta", "Robot wchodzi niezapowiedziany, podchodzi do solenizanta i składa życzenia — reakcja jest bezcenna, a nagranie z niej krąży potem po całej rodzinie."),
         faq_uniq=("Czy robot może wystąpić w domu lub ogrodzie?", "Tak — potrzebujemy tylko równej nawierzchni i trochę przestrzeni. Obsługujemy przyjęcia w domach, ogrodach i wynajętych salach.")),
    priv("robot-na-rocznice", "Robot na rocznicę", "na rocznicę", "Na rocznicy",
         sub="Rocznica ślubu, związku czy ważnego wydarzenia zasługuje na oprawę, której nikt się nie spodziewa. Robot humanoidalny złoży życzenia, wzniesie toast i poprowadzi taniec — a jubilaci dostaną wspomnienie na kolejne dekady.",
         uniq_scen=("Toast za jubilatów", "Robot wznosi toast i wygłasza przygotowaną przemowę o parze — wzruszenie i śmiech w idealnych proporcjach."),
         faq_uniq=("Czy robot może opowiedzieć historię pary?", "Tak — przygotowujemy z Wami krótką opowieść (jak się poznali, wspólne anegdoty), którą robot wplata w życzenia. Goście są zachwyceni.")),
    priv("robot-na-impreze-prywatna", "Robot na imprezę prywatną", "na imprezę prywatną", "Na imprezie",
         sub="Domówka premium, urodziny w wynajętej willi, prywatne przyjęcie w ogrodzie — robot humanoidalny to atrakcja, po której Twoja impreza stanie się legendą wśród znajomych.",
         uniq_scen=("Gość specjalny wieczoru", "Robot pojawia się jako niezapowiedziany gość — wita domowników, tańczy i rozmawia dzięki AI. Przez resztę wieczoru nikt nie mówi o niczym innym."),
         faq_uniq=("Ile miejsca potrzebuje robot na prywatnej imprezie?", "Wystarczy kilka metrów kwadratowych równej podłogi — salon, taras czy namiot imprezowy w zupełności wystarczą.")),
    priv("robot-na-wieczor-panienski", "Robot na wieczór panieński", "na wieczór panieński", "Na wieczorze panieńskim",
         sub="Wieczór panieński, którego nie przebije żadna inna ekipa: robot humanoidalny tańczy z panną młodą, prowadzi zabawy i pozuje do zdjęć, które rozgrzeją grupowy czat do czerwoności.",
         uniq_scen=("Taniec z panną młodą", "Robot zaprasza przyszłą pannę młodą do tańca — układ na dwie osoby, doping ekipy i nagranie, które będzie hitem wesela."),
         faq_uniq=("Czy robot poprowadzi zabawy na wieczorze panieńskim?", "Tak — robot może prowadzić quizy o parze, wyzwania taneczne i wznosić toasty. Program układamy z organizatorką wieczoru.")),
    priv("robot-na-bal-maturalny", "Robot na bal maturalny", "na bal maturalny", "Na balu",
         sub="Studniówka albo bal maturalny z robotem humanoidalnym to wydarzenie, które przejdzie do historii szkoły. G1 otwiera bal, tańczy z maturzystami i pozuje do zdjęć, które zaleją Instagrama jeszcze tej samej nocy.",
         uniq_scen=("Otwarcie balu", "Po polonezie robot wkracza na parkiet z własnym układem — moment, w którym cała sala wyciąga telefony. DJ ma potem łatwiej przez resztę nocy."),
         faq_uniq=("Czy robot może wystąpić w motywie przewodnim balu?", "Tak — pokaz możemy zgrać z motywem balu i playlistą DJ-a. Ustalamy szczegóły z komitetem organizacyjnym.")),
    priv("robot-na-komunie", "Robot na komunię", "na komunię", "Na przyjęciu komunijnym",
         sub="Przyjęcie komunijne z atrakcją, która zachwyci dzieci i zaskoczy dorosłych: robot humanoidalny tańczy, przybija piątki i pozuje do zdjęć — w tonie dopasowanym do rodzinnego charakteru uroczystości.",
         uniq_scen=("Atrakcja dla dzieci przy stole dorosłych", "Gdy dorośli świętują przy stole, robot zajmuje się młodszymi gośćmi: zabawy, tańce i piątki pod okiem operatora. Rodzice mają spokój, dzieci — najlepszy dzień w roku."),
         faq_uniq=("Czy pokaz będzie odpowiedni dla charakteru uroczystości?", "Tak — na przyjęciach komunijnych prowadzimy program w spokojnym, rodzinnym tonie, z akcentem na zabawy dla dzieci.")),
    priv("robot-na-chrzciny", "Robot na chrzciny", "na chrzciny", "Na przyjęciu",
         sub="Chrzciny gromadzą całą rodzinę — a robot humanoidalny daje wszystkim pokoleniom wspólną atrakcję: od dziadków po starsze rodzeństwo. Delikatny, rodzinny program z pamiątkowymi zdjęciami dla gości.",
         uniq_scen=("Pamiątkowe zdjęcia rodzinne", "Robot pozuje do zdjęć z każdą rodziną z osobna — po przyjęciu wszyscy goście mają wyjątkową pamiątkę z uroczystości."),
         faq_uniq=("Czy robot nie przestraszy najmłodszych?", "Operator prowadzi interakcje bardzo łagodnie, zaczynając z dystansu — dzieci szybko przechodzą od nieśmiałości do zachwytu. Niemowlęta obserwują z bezpiecznej odległości rodziców.")),
    priv("robot-na-dzien-dziecka", "Robot na Dzień Dziecka", "na Dzień Dziecka", "Na Dniu Dziecka",
         sub="Dzień Dziecka z prawdziwym robotem bije każdą dmuchańcową strefę: pokazy tańca, wspólne zabawy i piątki z humanoidem to atrakcja, którą dzieci będą wspominać cały rok — w szkole, firmie czy na osiedlu.",
         uniq_scen=("Zabawy z całą grupą", "Robot prowadzi zabawy ruchowe z dziećmi: powtarzanie gestów, wspólny taniec, wyzwania na refleks — energia grupy rośnie z minuty na minutę."),
         faq_uniq=("Czy obsługujecie firmowe Dni Dziecka?", "Tak — Dzień Dziecka dla rodzin pracowników to jeden z naszych najczęstszych formatów. Program łączy pokazy dla dzieci z atrakcjami dla rodziców."),
         guides_override="dzieci"),
    priv("robot-na-mikolajki", "Robot na mikołajki", "na mikołajki", "Na mikołajkach",
         sub="Robo-Mikołaj istnieje: G1 rozdaje prezenty, tańczy do świątecznych hitów i pozuje do zdjęć przy choince. Mikołajki firmowe, szkolne czy osiedlowe zyskują atrakcję, przy której dzieci zapominają o liście życzeń.",
         uniq_scen=("Rozdawanie prezentów", "Robot wręcza dzieciom prezenty — każde wręczenie to osobny mały pokaz i zdjęcie, które rodzice zachowają na lata."),
         faq_uniq=("Czy robot może wystąpić w świątecznym akcencie?", "Tak — czapka Mikołaja i świąteczna oprawa pokazu to standard w grudniu. Playlistę świąteczną też bierzemy na siebie."),
         guides_override="dzieci"),
    priv("robot-na-andrzejki", "Robot na andrzejki", "na andrzejki", "Na andrzejkach",
         sub="Andrzejki z robotem-wróżbitą? G1 przepowiada przyszłość z przymrużeniem oka, prowadzi zabawy andrzejkowe i tańczy z gośćmi — impreza, o której będzie się mówić do następnych andrzejek.",
         uniq_scen=("Wróżby od robota", "Robot-wróżbita przepowiada gościom przyszłość — zabawne, personalizowane wróżby generowane przez AI to hit każdej imprezy andrzejkowej."),
         faq_uniq=("Jak działają wróżby robota?", "Robot generuje zabawne przepowiednie dzięki AI — z humorem i bez powagi. Możemy dodać motywy związane z Waszą grupą czy firmą.")),
    priv("robot-na-halloween", "Robot na Halloween", "na Halloween", "Na imprezie halloweenowej",
         sub="Robot na Halloween to atrakcja z pogranicza science fiction i horroru — dokładnie tak, jak trzeba. G1 w mrocznej stylizacji wita gości, tańczy do halloweenowych hitów i robi wrażenie większe niż każdy kostium.",
         uniq_scen=("Mroczne powitanie", "Robot wyłania się z półmroku i wita gości — dreszczyk gwarantowany, a zaraz po nim śmiech i kolejka do zdjęć."),
         faq_uniq=("Czy robot może mieć halloweenową stylizację?", "Tak — lekkie elementy stylizacji i odpowiednia oprawa świetlno-muzyczna zamieniają pokaz w idealnie klimatyczne widowisko.")),
    priv("robot-na-sylwestra", "Robot na Sylwestra", "na Sylwestra", "W sylwestrową noc",
         sub="Sylwester z robotem humanoidalnym to wejście w nowy rok dosłownie z przyszłością: odliczanie z robotem, toast o północy i taniec do rana. Impreza, od której zaczną się wszystkie noworoczne rozmowy.",
         uniq_scen=("Odliczanie do północy", "Robot prowadzi odliczanie ostatnich sekund roku i wznosi toast z gośćmi — początek roku, jakiego nie miał nikt z Waszych znajomych."),
         faq_uniq=("Czy robot pracuje w noc sylwestrową?", "Tak — Sylwester to nasz sezon wysoki. Terminy rezerwują się najszybciej w roku, dlatego pytaj możliwie wcześnie.")),
    priv("robot-na-karnawal", "Robot na karnawał", "na karnawał", "Na balu karnawałowym",
         sub="Bal karnawałowy potrzebuje gwiazdy parkietu — a nikt nie tańczy tak, jak robot humanoidalny. G1 prowadzi pokazy taneczne, dołącza do korowodu i pozuje do zdjęć w karnawałowej scenerii.",
         uniq_scen=("Gwiazda parkietu", "Robot otwiera parkiet własnym układem i zaprasza gości do wspólnego tańca — od tej chwili parkiet nie pustoszeje do końca balu."),
         faq_uniq=("Czy robot zatańczy do muzyki na żywo?", "Tak — choreografie synchronizujemy z playlistą DJ-a lub repertuarem zespołu; wystarczy ustalić utwory z wyprzedzeniem.")),
    priv("robot-na-walentynki", "Robot na walentynki", "na walentynki", "W walentynki",
         sub="Walentynkowa niespodzianka, której nie przebije żaden bukiet: robot humanoidalny wyznaje uczucia w Twoim imieniu, wręcza prezent i zaprasza do tańca. Dla par — i dla lokali, które chcą walentynkowego szumu.",
         uniq_scen=("Wyznanie z przyszłości", "Robot podchodzi do wybranej osoby, wygłasza przygotowane wyznanie i wręcza kwiaty lub prezent — moment jak z filmu sci-fi, tylko na żywo."),
         faq_uniq=("Czy robot pomoże przy zaręczynach?", "Tak — pomagamy zaplanować zaręczyny z udziałem robota: od scenariusza po dyskretne nagranie całej niespodzianki.")),
    priv("robot-na-garden-party", "Robot na garden party", "na garden party", "Na garden party",
         sub="Garden party z klasą i z przyszłością: robot humanoidalny krąży wśród gości na tarasie, prowadzi pokazy na trawniku przy podeście i dodaje przyjęciu w ogrodzie charakteru, o którym sąsiedzi mogą tylko pomarzyć.",
         uniq_scen=("Popołudnie w ogrodzie", "Robot pracuje w rytmie przyjęcia: powitania przy wejściu, pokaz na podeście, swobodne interakcje przy stolikach — wszystko w letnim, niespiesznym tempie."),
         faq_uniq=("Czego robot potrzebuje w ogrodzie?", "Równej, utwardzonej strefy (taras, podest, kostka) i suchej pogody. Na wypadek deszczu ustalamy wariant pod zadaszeniem.")),
]

EXTRA_PAGES = chain_related(EVENTS) + chain_related(BRANZE) + chain_related(PRIVATE)
