# -*- coding: utf-8 -*-
"""Treści podstron SEO — część 1: usługi, role robota, miejsca i branże."""


def faq_price(x):
    return (f"Ile kosztuje robot {x}?",
            "Cena zależy od czasu obecności robota, zakresu pokazu i lokalizacji. Każda wycena jest indywidualna — napisz przez formularz lub zadzwoń, a w ciągu 24h dostaniesz konkretną ofertę.")


def faq_safe():
    return ("Czy robot jest bezpieczny dla uczestników?",
            "Tak — Unitree G1 ma czujniki unikania przeszkód i przez cały czas pracuje pod nadzorem certyfikowanego operatora 33bots, który kontroluje bezpieczną odległość od ludzi.")


def faq_operator():
    return ("Czy robot przyjeżdża z obsługą?",
            "Tak — w cenie wynajmu jest zawsze certyfikowany operator, który steruje robotem, dba o bezpieczeństwo i pomaga poprowadzić interakcje z gośćmi. Ty niczego nie musisz obsługiwać.")


def faq_transport():
    return ("Czy dojeżdżacie do naszego miasta?",
            "Tak — działamy w całej Polsce, a transport robota jest wliczony w cenę. Obsługujemy zarówno duże miasta, jak i mniejsze miejscowości.")


def faq_book(x):
    return (f"Jak wcześnie zarezerwować robota {x}?",
            "Najlepiej minimum 3–4 tygodnie przed datą wydarzenia. W szczycie sezonu eventowego (wiosna i jesień) terminy wypełniają się szybciej, więc warto pytać wcześniej.")


DEFAULTS = {
    "tiles_h2": "Atrakcja, która<br />pracuje na Twój cel",
    "scen_title": "Jak to wygląda w praktyce?",
    "related_intro": "Szukasz czegoś innego? Zobacz pełną ofertę wynajmu robota",
    "related": [("wypozyczenie-robota.html", "Wynajem robota"), ("atrakcje-na-event.html", "Wszystkie atrakcje")],
    "kontakt_h2": "Zarezerwuj robota<br />na swoje wydarzenie.",
    "video": "gesty",
    "guides": "default",
}


def mk(**kw):
    d = dict(DEFAULTS)
    d.update(kw)
    d.setdefault("schema_name", d["crumb"] + " — wynajem Unitree G1")
    d.setdefault("schema_desc", d["desc"].rstrip(" →"))
    d.setdefault("faq_h2", "Najczęstsze<br />pytania")
    return d


# ================================================================ USŁUGI

SERVICES = [
    mk(
        slug="atrakcje-na-event", crumb="Atrakcje na event",
        title="Atrakcje na event — robot humanoidalny Unitree G1 | 33bots",
        desc="Szukasz atrakcji na event? Robot humanoidalny Unitree G1: wita gości, tańczy, rozmawia z AI i pozuje do zdjęć. Dojazd w całej Polsce, operator w cenie →",
        keywords="atrakcje na event, atrakcja eventowa, atrakcje na imprezę firmową, nietypowe atrakcje na event, robot na event",
        eyebrow="Atrakcje eventowe · Robot humanoidalny · Cała Polska",
        h1="Atrakcja na event, która<br />przyćmi wszystkie inne.",
        sub="Fotobudki i barmani flair już nikogo nie zaskakują. Chodzący, tańczący i rozmawiający robot humanoidalny — wciąż tak. Unitree G1 to atrakcja eventowa, wokół której gromadzi się całe wydarzenie.",
        tiles_h2="Dlaczego robot wygrywa<br />z klasycznymi atrakcjami",
        tiles=[
            ("Efekt WOW", "Nikt obok niego nie przejdzie", "Większość gości nigdy nie widziała humanoida na żywo. Robot buduje wokół siebie tłum w kilka minut — bez zapowiedzi i bez zaproszeń."),
            ("Viral", "Content sam się robi", "Każda interakcja z robotem kończy się nagraniem. Twoje wydarzenie trafia na Instagram i TikTok jeszcze w trakcie jego trwania."),
            ("Elastyczność", "Jedna atrakcja, wiele ról", "Powitanie gości, pokaz tańca, rozmowy z AI, wspólne zdjęcia — robot płynnie zmienia rolę w trakcie wydarzenia, dopasowując się do agendy."),
        ],
        scen_title="Co robot robi na evencie?",
        scen_intro="Program pokazu układamy wspólnie z Tobą — pod charakter wydarzenia, agendę i publiczność. Najczęściej łączymy trzy elementy:",
        scens=[
            ("Powitanie i pierwsze wrażenie", "Robot staje przy wejściu i wita gości gestem oraz głosem. Od pierwszych sekund wiadomo, że to wydarzenie będzie inne niż wszystkie."),
            ("Interakcje i zdjęcia", "G1 podchodzi do gości, przybija piątki, gestykuluje i pozuje do zdjęć. To najdłużej działający magnes wydarzenia — kolejka do zdjęcia nie znika."),
            ("Pokaz choreografii", "Kulminacja programu: robot wykonuje układ taneczny zsynchronizowany z muzyką. Moment, który generuje najwięcej nagrań i braw."),
        ],
        faqs=[faq_price("na event"), faq_operator(), faq_safe(), faq_book("na event")],
        related_intro="Zobacz konkretne scenariusze wykorzystania robota",
        related=[("robot-na-targi.html", "Robot na targi"), ("robot-na-konferencje.html", "Robot na konferencję"), ("robot-na-impreze-firmowa.html", "Robot na imprezę firmową")],
        faq_h2="Pytania o atrakcje<br />na event",
        video="taniec",
    ),
    mk(
        slug="nowoczesne-atrakcje-eventowe", crumb="Nowoczesne atrakcje eventowe",
        title="Nowoczesne atrakcje eventowe — robot humanoidalny z AI | 33bots",
        desc="Nowoczesne atrakcje eventowe 2026: robot humanoidalny Unitree G1 z AI. Technologia, która robi realne wrażenie na gościach. Transport i operator w cenie →",
        keywords="nowoczesne atrakcje eventowe, atrakcje technologiczne na event, innowacyjne atrakcje na imprezę, atrakcje przyszłości, robot z AI na event",
        eyebrow="Technologia · AI · Atrakcje eventowe",
        h1="Nowoczesne atrakcje eventowe —<br />robot, nie gadżet.",
        sub="Gogle VR i drukarki 3D były nowoczesne dekadę temu. Dziś granicę technologii wyznaczają roboty humanoidalne — i właśnie taką atrakcję możesz mieć na swoim wydarzeniu, z pełną obsługą.",
        tiles_h2="Technologia, którą goście<br />zapamiętają na lata",
        tiles=[
            ("Premiera", "Coś, czego jeszcze nie widzieli", "Roboty humanoidalne dopiero wchodzą do Polski. Dla większości Twoich gości spotkanie z G1 będzie pierwszym kontaktem z chodzącym robotem w życiu."),
            ("AI", "Rozmawia po polsku", "Dzięki integracji z AI robot prowadzi rozmowy z gośćmi w języku polskim — odpowiada na pytania, żartuje i opowiada o Twojej marce."),
            ("Wizerunek", "Twoja marka = innowacja", "Firma, która zaprasza na scenę humanoida, automatycznie pozycjonuje się jako technologiczny lider. Ten przekaz zostaje w głowach na długo."),
        ],
        scen_intro="Nowoczesna atrakcja nie może być tylko dekoracją — musi angażować. Dlatego pokaz G1 budujemy wokół interakcji:",
        scens=[
            ("Pokaz możliwości", "Chód, gesty, dynamiczne ruchy i choreografia — kilkuminutowe show, które pokazuje, co potrafi współczesna robotyka."),
            ("Rozmowy z AI", "Goście zadają pytania, robot odpowiada głosem po polsku. To moment, w którym technologia przestaje być ciekawostką, a zaczyna być doświadczeniem."),
            ("Strefa zdjęć z robotem", "G1 pozuje, przybija piątki i gestykuluje. Strefa foto z humanoidem to najczęściej odwiedzany punkt każdego wydarzenia."),
        ],
        faqs=[
            ("Czym robot różni się od innych atrakcji technologicznych?", "VR czy hologramy angażują jedną osobę na raz i wymagają tłumaczenia. Robot humanoidalny działa na całą salę jednocześnie — widać go z daleka, reaguje na ludzi i nie potrzebuje instrukcji obsługi po stronie gościa."),
            faq_price("z AI na event"), faq_operator(), faq_book("na wydarzenie"),
        ],
        guides="ai", video="spacer",
        related_intro="Zobacz, jak robot sprawdza się na konkretnych wydarzeniach",
        related=[("robot-ai-na-wydarzenie.html", "Robot AI na wydarzenie"), ("show-robotow.html", "Show robotów")],
    ),
    mk(
        slug="show-robotow", crumb="Show robotów",
        title="Show robotów — pokaz robota humanoidalnego na event | 33bots",
        desc="Show robotów na Twoim evencie: taniec, dynamiczne ruchy i interakcje Unitree G1 z publicznością. Pokaz sceniczny z operatorem, cała Polska →",
        keywords="show robotów, pokaz robotów, pokaz robota humanoidalnego, występ robota, taniec robota, show robota na event",
        eyebrow="Pokaz sceniczny · Choreografia · Interakcje",
        h1="Show robotów —<br />pokaz, który kradnie scenę.",
        sub="Kilkuminutowy, wyreżyserowany występ robota humanoidalnego: choreografia do muzyki, dynamiczne ruchy i interakcje z publicznością. Idealne otwarcie gali, przerywnik konferencji albo finał wieczoru.",
        tiles_h2="Występ, o którym mówi się<br />długo po evencie",
        tiles=[
            ("Scena", "Gotowy punkt programu", "Show robota to zamknięty, dopracowany segment agendy — wiesz dokładnie, ile trwa i co się wydarzy. Zero improwizacji tam, gdzie liczy się timing."),
            ("Muzyka", "Choreografia do rytmu", "Układy taneczne G1 są zsynchronizowane z muzyką. Możemy dopasować utwór do charakteru wydarzenia — od gali po festiwal."),
            ("Publiczność", "Interakcja po występie", "Po pokazie robot schodzi „w tłum”: zdjęcia, piątki, rozmowy. Show płynnie przechodzi w strefę interakcji, która pracuje do końca eventu."),
        ],
        scen_title="Jak wygląda show robota?",
        scen_intro="Standardowy pokaz trwa od kilku do kilkunastu minut i można go powtarzać w blokach w trakcie wydarzenia:",
        scens=[
            ("Wejście robota", "G1 wchodzi na scenę o własnych siłach — sam ten moment wywołuje aplauz. Chodzący humanoid na żywo robi większe wrażenie niż jakikolwiek materiał wideo."),
            ("Układ choreograficzny", "Serce pokazu: taniec zsynchronizowany z muzyką, dynamiczne ruchy ramion i korpusu. Publiczność nagrywa, bije brawo i nie odrywa wzroku."),
            ("Finał z publicznością", "Robot kłania się, macha i zaprasza gości do wspólnych zdjęć. Energia z sceny przenosi się prosto do strefy foto."),
        ],
        faqs=[
            ("Ile trwa show robotów?", "Pojedynczy pokaz trwa zwykle 5–15 minut. Najczęściej łączymy 2–3 krótkie bloki pokazowe z czasem na interakcje i zdjęcia między nimi — tak robot pracuje przez całe wydarzenie."),
            ("Czy show można dopasować do naszego wydarzenia?", "Tak — dobieramy muzykę, moment wejścia i długość pokazu do Waszej agendy. Robot może też pojawić się z brandingiem Twojej marki."),
            faq_price("na show"), faq_safe(),
        ],
        video="taniec",
        related_intro="Show robota świetnie działa na galach i konferencjach",
        related=[("robot-na-gale.html", "Robot na galę"), ("robot-na-wystep-sceniczny.html", "Występ sceniczny robota")],
    ),
    mk(
        slug="wynajem-robota-do-firmy", crumb="Wynajem robota do firmy",
        title="Wynajem robota do firmy — eventy firmowe i marketing | 33bots",
        desc="Wynajem robota humanoidalnego do firmy: eventy wewnętrzne, spotkania z klientami, content marketingowy i employer branding. Operator w cenie, dojazd według lokalizacji →",
        keywords="wynajem robota do firmy, robot dla firmy, robot na spotkanie firmowe, robot do biura, wynajem robota humanoidalnego dla firm",
        eyebrow="B2B · Eventy firmowe · Marketing",
        h1="Wynajem robota do firmy —<br />technologia, która sprzedaje.",
        sub="Robot humanoidalny w firmie to nie tylko atrakcja na imprezę. To narzędzie: przyciąga klientów na dni otwarte, ożywia spotkania handlowe, generuje content marketingowy i wzmacnia wizerunek pracodawcy.",
        tiles_h2="Jeden robot,<br />wiele zastosowań w firmie",
        tiles=[
            ("Eventy", "Imprezy i spotkania firmowe", "Integracja, jubileusz, wigilia firmowa czy targi wewnętrzne — robot podnosi rangę każdego wydarzenia i daje pracownikom temat do rozmów na tygodnie."),
            ("Marketing", "Content i kampanie", "Sesja z robotem w Twoim biurze albo materiał wideo z G1 w roli głównej — content z humanoidem osiąga zasięgi, których nie da się kupić w media planie."),
            ("Klienci", "Spotkania, które się pamięta", "Zaproszenie klientów na prezentację z udziałem robota to pewny sposób na frekwencję — i na to, że Twoja oferta zostanie zapamiętana."),
        ],
        scen_intro="Współpracę z firmami prowadzimy elastycznie — od jednorazowego pokazu po cykliczne aktywacje:",
        scens=[
            ("Wydarzenie firmowe", "Robot pojawia się na Waszym evencie: wita gości, prowadzi pokaz choreografii i pozuje do zdjęć. Pełna obsługa po naszej stronie."),
            ("Aktywacja marketingowa", "G1 z brandingiem Twojej marki pracuje w punkcie sprzedaży, na dniach otwartych albo w kampanii wideo. Robot staje się twarzą akcji promocyjnej."),
            ("Materiały wewnętrzne i EB", "Nagrania z robotem wzmacniają komunikację rekrutacyjną i employer branding — pokazują firmę, która realnie sięga po nowe technologie."),
        ],
        faqs=[
            ("Czy robot może mieć logo naszej firmy?", "Tak — G1 może wystąpić z brandingiem Twojej marki: logo i elementy identyfikacji na robocie lub w jego otoczeniu. To jedna z najczęściej wybieranych opcji przez firmy."),
            faq_price("dla firmy"), faq_operator(), faq_transport(),
        ],
        guides="marketing", video="branding",
        related_intro="Zobacz scenariusze dla firm",
        related=[("robot-employer-branding.html", "Robot w employer brandingu"), ("robot-na-impreze-firmowa.html", "Robot na imprezę firmową")],
    ),
    mk(
        slug="wynajem-robotow", crumb="Wynajem robotów",
        title="Wynajem robotów humanoidalnych na eventy — cała Polska | 33bots",
        desc="Wynajem robotów humanoidalnych Unitree G1 na eventy, targi, konferencje i imprezy. Certyfikowany operator i dojazd w całej Polsce w całej Polsce →",
        keywords="wynajem robotów, wynajem robotów humanoidalnych, wypożyczalnia robotów, roboty na wynajem, wynajem robota na event",
        eyebrow="Wynajem · Unitree G1 · Cała Polska",
        h1="Wynajem robotów —<br />humanoid na Twój event.",
        sub="Wynajmujemy roboty humanoidalne Unitree G1 na wydarzenia w całej Polsce. W cenie zawsze: certyfikowany operator, transport, ubezpieczenie i program pokazu dopasowany do Twojego eventu.",
        tiles_h2="Wynajem bez ryzyka<br />i bez niespodzianek",
        tiles=[
            ("All inclusive", "Operator w cenie, dojazd według lokalizacji", "Nie kupujesz sprzętu — kupujesz gotowe widowisko. Przyjeżdżamy, rozstawiamy się, prowadzimy pokaz i sprzątamy po sobie. Ty zajmujesz się gośćmi."),
            ("Zasięg", "Cała Polska", "Warszawa, Kraków, Trójmiasto, Śląsk — i każde miejsce pomiędzy. Dojazd jest wliczony w cenę wynajmu, bez ukrytych kosztów."),
            ("Pewność", "Sprawdzony scenariusz", "Za nami dziesiątki eventów: targi, gale, konferencje, wesela. Wiemy, co działa na publiczność i jak ułożyć pokaz pod Twoją agendę."),
        ],
        scen_title="Jak przebiega wynajem?",
        scen_intro="Od zapytania do pokazu — proces jest prosty i przewidywalny:",
        scens=[
            ("1. Zapytanie i wycena", "Piszesz przez formularz lub dzwonisz. W ciągu 24h dostajesz wycenę dopasowaną do terminu, lokalizacji i czasu trwania pokazu."),
            ("2. Ustalenie scenariusza", "Wspólnie ustalamy program: momenty wejścia robota, choreografię, interakcje i ewentualny branding. Dostajesz konkretny plan minuta po minucie."),
            ("3. Realizacja", "W dniu wydarzenia przyjeżdżamy odpowiednio wcześniej, testujemy wszystko na miejscu i prowadzimy pokaz. Po evencie otrzymujesz też nagrania z robotem."),
        ],
        faqs=[
            ("Jakie roboty wynajmujecie?", "Naszym głównym robotem jest Unitree G1 — humanoid o wzroście 130 cm, który chodzi, tańczy, gestykuluje i dzięki AI rozmawia po polsku. To obecnie najbardziej widowiskowy robot dostępny na polskim rynku eventowym."),
            faq_price("na wynajem"), faq_transport(), faq_book("na wydarzenie"),
        ],
        guides="cena", video="spacer",
        related_intro="Sprawdź wynajem w swoim mieście",
        related=[("robot-wynajem-warszawa.html", "Warszawa"), ("robot-wynajem-krakow.html", "Kraków"), ("wypozyczenie-robota.html", "Pełna oferta")],
    ),
    mk(
        slug="robot-dla-agencji-eventowych", crumb="Robot dla agencji eventowych",
        title="Robot dla agencji eventowych — podwykonawstwo pokazów | 33bots",
        desc="Robot humanoidalny dla agencji eventowych: sprawdzony podwykonawca pokazów Unitree G1. Materiały dla klienta, rider techniczny, cała Polska →",
        keywords="robot dla agencji eventowych, atrakcje dla agencji eventowej, podwykonawca atrakcji eventowych, robot humanoidalny dla agencji",
        eyebrow="B2B · Agencje eventowe · Podwykonawstwo",
        h1="Robot dla agencji eventowych —<br />wow-efekt dla Twojego klienta.",
        sub="Szukasz atrakcji, która wygra przetarg i zachwyci klienta końcowego? Współpracujemy z agencjami eventowymi w całej Polsce — dostarczamy pokaz robota humanoidalnego jako niezawodny, kompletny moduł Twojego wydarzenia.",
        tiles_h2="Partner, nie tylko<br />dostawca atrakcji",
        tiles=[
            ("Oferta", "Materiały do prezentacji", "Dostajesz od nas gotowe materiały — zdjęcia, wideo i opisy pokazu — które możesz wpiąć prosto do oferty dla swojego klienta."),
            ("Rider", "Pełna specyfikacja techniczna", "Wymogi przestrzenne, zasilanie, czasy montażu — wszystko dostajesz z wyprzedzeniem w formie ridera. Twoja produkcja wie dokładnie, czego się spodziewać."),
            ("Niezawodność", "Backup i doświadczenie", "Wiemy, że na evencie klienta nie ma miejsca na wpadki. Przyjeżdżamy z zapasem czasu, sprzętem backupowym i scenariuszem awaryjnym."),
        ],
        scen_title="Jak współpracujemy z agencjami?",
        scen_intro="Dopasowujemy się do Twojego procesu — od briefu po raport z realizacji:",
        scens=[
            ("Brief i oferta", "Wysyłasz brief wydarzenia, my odsyłamy propozycję pokazu z wyceną i materiałami do prezentacji. Możemy też wziąć udział w spotkaniu z Twoim klientem."),
            ("Produkcja", "Współpracujemy z Twoim technicznym: rider, próby, timing. Robot może wystąpić z brandingiem klienta końcowego."),
            ("Realizacja i materiały", "Prowadzimy pokaz zgodnie ze scenariuszem, a po evencie przekazujemy nagrania i zdjęcia, które możesz wykorzystać w raporcie dla klienta."),
        ],
        faqs=[
            ("Czy oferujecie stawki partnerskie dla agencji?", "Tak — przy stałej współpracy i przy realizacjach cyklicznych oferujemy warunki partnerskie. Napisz do nas z krótkim opisem swoich projektów."),
            ("Czy możecie wystąpić „pod marką” agencji?", "Tak — na evencie działamy jako część Twojego zespołu produkcyjnego. Branding, komunikacja i kontakt z klientem końcowym pozostają po Twojej stronie."),
            faq_price("na event klienta"), faq_transport(),
        ],
        video="branding",
        related_intro="Zobacz nasze realizacje i case studies",
        related=[("realizacje-wideo.html", "Realizacje wideo"), ("case-study-lexai.html", "Case study")],
    ),
    mk(
        slug="robot-employer-branding", crumb="Robot w employer brandingu",
        title="Robot w employer brandingu — targi pracy i rekrutacja | 33bots",
        desc="Robot humanoidalny w employer brandingu: targi pracy, dni otwarte, onboarding i content rekrutacyjny. Przyciągnij kandydatów technologią →",
        keywords="robot employer branding, robot na targi pracy, atrakcja na targi pracy, employer branding technologia, robot rekrutacja",
        eyebrow="HR · Employer branding · Rekrutacja",
        h1="Robot w employer brandingu —<br />kandydaci przyjdą sami.",
        sub="Na targach pracy każde stoisko rozdaje gadżety. Tylko jedno ma chodzącego robota humanoidalnego. Robot w employer brandingu to najkrótsza droga, by kandydaci zapamiętali Twoją firmę — i uwierzyli w jej technologiczne ambicje.",
        tiles_h2="EB, który widać<br />z drugiego końca hali",
        tiles=[
            ("Targi pracy", "Kolejka do Twojego stoiska", "Robot buduje ruch przy stoisku szybciej niż jakikolwiek konkurs. Rekruterzy rozmawiają z kandydatami, którzy sami podeszli — to zupełnie inna rozmowa."),
            ("Wizerunek", "Dowód, nie deklaracja", "Każda firma pisze w ogłoszeniach o innowacyjności. Humanoid na stoisku to nie slogan, tylko namacalny dowód, że technologia jest Wam bliska."),
            ("Content", "Materiały rekrutacyjne", "Nagrania z robotem zasilają social media employer brandingowe na tygodnie — od LinkedIna po TikToka rekrutacyjnego."),
        ],
        scen_intro="Robot wspiera działania EB na kilku poziomach — od pojedynczego wydarzenia po całą kampanię:",
        scens=[
            ("Targi pracy i job fairy", "G1 pracuje przy Twoim stoisku: wita kandydatów, pozuje do zdjęć i rozmawia dzięki AI. Zebrane zainteresowanie zamienia się w rozmowy z rekruterami."),
            ("Dni otwarte i onboarding", "Robot wita nowych pracowników lub gości dni otwartych — pierwszy dzień w firmie zaczyna się od momentu, o którym opowiedzą znajomym."),
            ("Kampania rekrutacyjna", "Sesja wideo i foto z robotem w Waszym biurze daje unikalny content do ogłoszeń, karier-page'a i social mediów."),
        ],
        faqs=[
            ("Czy robot może rozmawiać z kandydatami o firmie?", "Tak — dzięki integracji z AI robot może opowiadać o firmie, odpowiadać na pytania o rekrutację i zapraszać do rozmowy z zespołem HR. Treści przygotowujemy wspólnie z Wami."),
            faq_price("na targi pracy"), faq_operator(), faq_book("na targi pracy"),
        ],
        blog_link=("blog-robot-na-targi-pracy.html", "robot na targach pracy — jak przyciągnąć kandydatów"),
        guides="marketing", video="powitanie",
        related_intro="Powiązane scenariusze",
        related=[("robot-na-targi-pracy.html", "Robot na targi pracy"), ("wynajem-robota-do-firmy.html", "Robot do firmy")],
    ),
]

# ================================================================ ROLE

ROLES = [
    mk(
        slug="robot-humanoidalny-na-event", crumb="Robot humanoidalny na event",
        title="Robot humanoidalny na event — wynajem Unitree G1 | 33bots",
        desc="Robot humanoidalny na event: Unitree G1 chodzi, tańczy, gestykuluje i rozmawia z gośćmi. Wynajem z operatorem i transportem w całej Polsce →",
        keywords="robot humanoidalny na event, wynajem robota humanoidalnego, humanoid na event, robot humanoidalny wynajem, Unitree G1 event",
        eyebrow="Humanoid · Unitree G1 · Wynajem",
        h1="Robot humanoidalny na event —<br />prawdziwy, chodzący humanoid.",
        sub="Nie ekran, nie hologram, nie maskotka. Unitree G1 to pełnoprawny robot humanoidalny: 130 cm wzrostu, płynny chód, dynamiczna choreografia i rozmowy z gośćmi dzięki AI. Na żywo robi wrażenie, którego nie odda żadne wideo.",
        tiles_h2="Dlaczego właśnie<br />humanoid?",
        tiles=[
            ("Forma", "Człowiek, ale robot", "Humanoidalna sylwetka sprawia, że goście reagują emocjonalnie — machają, witają się, rozmawiają. Żadna inna technologia nie buduje takiej relacji z publicznością."),
            ("Ruch", "Chodzi naprawdę", "G1 porusza się na dwóch nogach: chodzi między gośćmi, obraca się, kuca i tańczy. Sam widok idącego humanoida zatrzymuje ludzi w pół kroku."),
            ("AI", "Rozmawia po polsku", "Zapytaj go o cokolwiek — robot odpowiada głosem, żartuje i prowadzi rozmowę. Połączenie fizycznej obecności i AI to doświadczenie z zupełnie innej półki."),
        ],
        scen_intro="Humanoid odnajduje się w każdej roli eventowej — od witacza po gwiazdę wieczoru:",
        scens=[
            ("Gospodarz strefy", "Robot pracuje w wyznaczonej strefie: wita gości, odpowiada na pytania i pozuje do zdjęć. Strefa z humanoidem to naturalny punkt spotkań każdego eventu."),
            ("Pokaz sceniczny", "Choreografia zsynchronizowana z muzyką — kilkuminutowe show, które można powtarzać w blokach przez cały czas trwania wydarzenia."),
            ("Spacer między gośćmi", "G1 w ruchu, w asyście operatora, przechodzi przez przestrzeń eventu. Tam, gdzie się pojawia, natychmiast rośnie tłum."),
        ],
        faqs=[
            ("Jaki robot humanoidalny występuje na evencie?", "Pracujemy z Unitree G1 — najnowocześniejszym humanoidem dostępnym komercyjnie w Polsce. Ma 130 cm wzrostu, 23+ stopnie swobody ruchu i dzięki integracji z AI rozmawia po polsku."),
            faq_price("humanoidalny na event"), faq_safe(), faq_transport(),
        ],
        blog_link=("blog-co-potrafi-robot-humanoidalny.html", "co potrafi robot humanoidalny — 12 umiejętności G1"),
        video="spacer",
        related_intro="Poznaj role, w których występuje humanoid",
        related=[("robot-konferansjer.html", "Robot konferansjer"), ("robot-tancerz.html", "Robot tancerz"), ("robot-witajacy-gosci.html", "Robot witający gości")],
    ),
    mk(
        slug="robot-ai-na-wydarzenie", crumb="Robot AI na wydarzenie",
        title="Robot AI na wydarzenie — humanoid rozmawiający po polsku | 33bots",
        desc="Robot AI na wydarzenie: Unitree G1 z sztuczną inteligencją rozmawia z gośćmi po polsku, odpowiada na pytania i opowiada o Twojej marce →",
        keywords="robot AI na wydarzenie, robot ze sztuczną inteligencją, robot rozmawiający po polsku, AI na event, robot z chatgpt na event",
        eyebrow="Sztuczna inteligencja · Rozmowy · Interakcja",
        h1="Robot AI na wydarzenie —<br />humanoid, z którym się rozmawia.",
        sub="Połączyliśmy robota humanoidalnego z nowoczesnymi modelami AI. Efekt: G1 prowadzi płynne rozmowy po polsku — odpowiada na pytania gości, żartuje, opowiada o Twojej firmie i produkcie. Na żywo, głosem, bez scenariusza.",
        tiles_h2="AI, którą można<br />spotkać osobiście",
        tiles=[
            ("Rozmowa", "Prawdziwy dialog, nie nagrania", "Robot nie odtwarza formułek — rozumie pytania i odpowiada na bieżąco. Każda rozmowa jest inna, a goście testują go z rosnącym niedowierzaniem."),
            ("Twoja marka", "Opowie o Twojej ofercie", "Zasilamy AI wiedzą o Twojej firmie: robot odpowiada na pytania o produkty, usługi czy rekrutację. To najbardziej angażująca prezentacja oferty, jaką widzieli Twoi klienci."),
            ("Pokaz", "Pokaz + rozmowa = komplet", "Choreografia przyciąga tłum, rozmowy z AI go zatrzymują. Te dwa elementy razem sprawiają, że robot pracuje na Twój cel przez cały event."),
        ],
        scen_intro="Rozmawiający robot zmienia dynamikę każdego wydarzenia — oto najczęstsze zastosowania:",
        scens=[
            ("Q&A z gośćmi", "Goście podchodzą i zadają pytania — od „ile masz lat” po pytania o Twoją ofertę. Robot odpowiada głosem, po polsku, z humorem."),
            ("Asystent stoiska", "Na targach robot odpowiada na powtarzalne pytania o produkt i przekierowuje rozmowy do handlowców, gdy robi się konkretnie."),
            ("Wywiad na scenie", "Prowadzący rozmawia z robotem przed publicznością — zaskakujące odpowiedzi AI to gotowy, widowiskowy punkt agendy."),
        ],
        faqs=[
            ("Jak działa AI w robocie?", "Robot korzysta z nowoczesnych modeli językowych połączonych z syntezą mowy. Rozumie pytania zadawane po polsku i odpowiada naturalnym głosem w czasie rzeczywistym — a my możemy zasilić go wiedzą o Twojej marce."),
            ("Czy robot zrozumie każde pytanie?", "AI radzi sobie z ogromną większością pytań, także tych zadanych „podchwytliwie”. Nad przebiegiem rozmów zawsze czuwa operator, który w razie potrzeby moderuje interakcję."),
            faq_price("z AI"), faq_operator(),
        ],
        guides="ai", video="gesty",
        related_intro="Zobacz robota AI w konkretnych rolach",
        related=[("robot-recepcjonista.html", "Robot recepcjonista"), ("robot-prelegent.html", "Robot prelegent")],
    ),
    mk(
        slug="robot-konferansjer", crumb="Robot konferansjer",
        title="Robot konferansjer — humanoid współprowadzący event | 33bots",
        desc="Robot konferansjer na event: Unitree G1 współprowadzi wydarzenie, zapowiada punkty programu i rozmawia z prowadzącym. Nowy wymiar konferansjerki →",
        keywords="robot konferansjer, robot prowadzący event, konferansjer na event, robot na scenie, współprowadzący robot",
        eyebrow="Scena · Konferansjerka · Duet z prowadzącym",
        h1="Robot konferansjer —<br />duet, który zapamiętają.",
        sub="Wyobraź sobie otwarcie gali, w którym konferansjer wita gości… wspólnie z robotem humanoidalnym. G1 zapowiada punkty programu, wymienia się żartami z prowadzącym i dodaje wydarzeniu rozgłosu jeszcze przed pierwszym punktem agendy.",
        tiles_h2="Konferansjerka, jakiej<br />jeszcze nie było",
        tiles=[
            ("Duet", "Człowiek + robot na scenie", "Najlepiej działa w parze: prowadzący nadaje rytm, robot zaskakuje ripostami AI i gestami. Dialog człowieka z humanoidem to widowisko sam w sobie."),
            ("Agenda", "Zapowiedzi punktów programu", "Robot może zapowiadać prelegentów, ogłaszać przerwy i zapraszać na kolejne części wydarzenia — każda zapowiedź to mały pokaz."),
            ("PR", "Gotowy news z wydarzenia", "„Event współprowadził robot” — to zdanie samo pisze komunikaty prasowe i posty. Media i uczestnicy niosą tę historię dalej."),
        ],
        scen_intro="Robot nie zastępuje konferansjera — czyni go nie do zapomnienia. Typowy przebieg współpracy na scenie:",
        scens=[
            ("Otwarcie wydarzenia", "Prowadzący zapowiada „wyjątkowego współprowadzącego” — na scenę o własnych siłach wchodzi G1. Aplauz gwarantowany, uwaga publiczności zdobyta na resztę dnia."),
            ("Dialogi między punktami", "Krótkie, wyreżyserowane wymiany zdań między prowadzącym a robotem spinają agendę i utrzymują energię między wystąpieniami."),
            ("Finał i pożegnanie", "Robot żegna gości układem tanecznym albo wspólnym zdjęciem ze sceny — mocne domknięcie wydarzenia."),
        ],
        faqs=[
            ("Czy robot może samodzielnie prowadzić event?", "Rekomendujemy formułę duetu: człowiek prowadzi, robot współprowadzi. To daje pewność timingu i pełne bezpieczeństwo programu, a jednocześnie cały efekt WOW. Wybrane punkty robot może poprowadzić sam."),
            ("Skąd robot wie, co powiedzieć?", "Część kwestii przygotowujemy wspólnie z Wami przed wydarzeniem, a część powstaje na żywo dzięki AI — stąd naturalne, czasem zaskakująco błyskotliwe riposty."),
            faq_price("konferansjer"), faq_book("do prowadzenia wydarzenia"),
        ],
        blog_link=("blog-czy-robot-moze-prowadzic-event.html", "czy robot może prowadzić event?"),
        guides="ai", video="gesty",
        related_intro="Podobne role sceniczne robota",
        related=[("robot-prowadzacy-event.html", "Robot prowadzący event"), ("robot-prezenter.html", "Robot prezenter")],
    ),
    mk(
        slug="robot-prezenter", crumb="Robot prezenter",
        title="Robot prezenter — humanoid prezentujący produkt i markę | 33bots",
        desc="Robot prezenter: Unitree G1 prezentuje produkt, usługę lub markę na scenie i przy stoisku. Prezentacja, którą publiczność nagrywa telefonami →",
        keywords="robot prezenter, robot prezentujący produkt, prezentacja produktu robot, robot do prezentacji, humanoid prezenter",
        eyebrow="Prezentacje · Premiery · Stoiska",
        h1="Robot prezenter —<br />Twój produkt w centrum uwagi.",
        sub="Najtrudniejsze w każdej prezentacji jest przyciągnięcie i utrzymanie uwagi. Robot prezenter rozwiązuje oba problemy: gdy humanoid opowiada o Twoim produkcie, publiczność nie tylko słucha — nagrywa.",
        tiles_h2="Prezentacja, której<br />nikt nie przewinie",
        tiles=[
            ("Uwaga", "100% sali patrzy na scenę", "Prezentacja prowadzona przez robota to pattern-break: mózg nie umie jej zignorować. Twój przekaz trafia do skupionej, zaciekawionej publiczności."),
            ("Przekaz", "Skrypt pod Twój produkt", "Wspólnie przygotowujemy treść prezentacji: kluczowe cechy, korzyści, call-to-action. Robot dowozi przekaz słowo w słowo, za każdym razem z tą samą energią."),
            ("Zasięg", "Prezentacja żyje w sieci", "Nagrania z robotem prezentującym Twój produkt rozchodzą się w social mediach — prezentacja pracuje długo po zakończeniu eventu."),
        ],
        scen_intro="Robot prezentuje wszędzie tam, gdzie liczy się uwaga publiczności:",
        scens=[
            ("Premiera produktu", "G1 odsłania i prezentuje nowość na scenie — moment premiery zyskuje oprawę, o której piszą media branżowe."),
            ("Prezentacje przy stoisku", "Na targach robot cyklicznie prezentuje ofertę przy Twoim stoisku, zbierając za każdym razem świeżą publiczność."),
            ("Materiał wideo", "Robot prezenter w Twoim spocie lub na social media — unikalny format, który wyróżnia markę na tle konkurencji."),
        ],
        faqs=[
            ("Czy robot nauczy się prezentacji naszego produktu?", "Tak — przygotowujemy skrypt wspólnie z Wami, a robot wygłasza go głosem z odpowiednią gestykulacją. Dzięki AI poradzi sobie też z pytaniami publiczności po prezentacji."),
            faq_price("prezenter"), faq_operator(), faq_transport(),
        ],
        video="gesty",
        related_intro="Zobacz pokrewne role robota",
        related=[("robot-prelegent.html", "Robot prelegent"), ("robot-na-premiere-produktu.html", "Robot na premierę produktu")],
    ),
    mk(
        slug="robot-prelegent", crumb="Robot prelegent",
        title="Robot prelegent — wystąpienie robota na konferencji | 33bots",
        desc="Robot prelegent na konferencję: Unitree G1 wygłasza wystąpienie, odpowiada na pytania sali i robi keynote, o którym będzie się mówić →",
        keywords="robot prelegent, robot na konferencji, wystąpienie robota, keynote robot, prelekcja robota, robot mówca",
        eyebrow="Konferencje · Keynote · Q&A",
        h1="Robot prelegent —<br />keynote, który przejdzie do historii.",
        sub="Sto konferencji rocznie, wszędzie te same slajdy. A teraz wyobraź sobie punkt agendy: „Wystąpienie robota humanoidalnego”. G1 wygłasza prelekcję głosem, gestykuluje jak mówca i odpowiada na pytania sali dzięki AI.",
        tiles_h2="Punkt agendy, dla którego<br />przychodzi się na event",
        tiles=[
            ("Frekwencja", "Sala pełna na Twoim slocie", "Wystąpienie robota przyciąga uczestników jak żaden inny punkt programu — to slot, na który nikt się nie spóźnia."),
            ("Treść", "Merytoryka + widowisko", "Robot może mówić o technologii, przyszłości pracy albo o Twojej branży — treść przygotowujemy wspólnie, a forma broni się sama."),
            ("Q&A", "Odpowiada na pytania sali", "Po prelekcji robot bierze pytania z sali i odpowiada na żywo dzięki AI. To najbardziej wyczekiwany moment całego wystąpienia."),
        ],
        scen_intro="Wystąpienie robota układamy jak dobry keynote — z dramaturgią:",
        scens=[
            ("Wejście i hook", "Robot wchodzi na scenę o własnych siłach i zaczyna mówić. Pierwsze 30 sekund wystarcza, by cała sala sięgnęła po telefony."),
            ("Prelekcja", "10–15 minut treści przygotowanej pod Twoje wydarzenie — z gestykulacją, pauzami i humorem. Robot mówi płynnie po polsku."),
            ("Q&A i interakcje", "Pytania z sali, odpowiedzi na żywo, a na koniec zdjęcia z prelegentem-robotem w kuluarach. Networking załatwia się sam."),
        ],
        faqs=[
            ("O czym może mówić robot prelegent?", "O wszystkim, co ustalimy: sztucznej inteligencji, robotyce, przyszłości Twojej branży albo o temacie przewodnim konferencji. Skrypt przygotowujemy wspólnie, a AI pozwala robotowi odpowiadać na pytania spoza niego."),
            ("Ile trwa wystąpienie robota?", "Standardowo 10–20 minut plus sesja Q&A. Długość dopasowujemy do agendy — od krótkiego 5-minutowego akcentu po pełny slot keynote."),
            faq_price("prelegent"), faq_safe(),
        ],
        guides="ai", video="gesty",
        related_intro="Robot świetnie działa na konferencjach",
        related=[("robot-na-konferencje.html", "Robot na konferencję"), ("robot-konferansjer.html", "Robot konferansjer")],
    ),
    mk(
        slug="robot-prowadzacy-event", crumb="Robot prowadzący event",
        title="Robot prowadzący event — humanoid jako host wydarzenia | 33bots",
        desc="Robot prowadzący event: Unitree G1 jako host wydarzenia — otwiera, zapowiada, angażuje publiczność i domyka program. Z operatorem w cenie →",
        keywords="robot prowadzący event, robot host, prowadzenie eventu robot, robot gospodarz wydarzenia, robot prowadzi imprezę",
        eyebrow="Hosting · Scena · Program wydarzenia",
        h1="Robot prowadzący event —<br />gospodarz z przyszłości.",
        sub="Od otwarcia po finał: robot humanoidalny w roli gospodarza wydarzenia. Wita uczestników, zapowiada kolejne punkty, angażuje publiczność między nimi — i sprawia, że Twój event ma motyw przewodni, o którym mówią wszyscy.",
        tiles_h2="Event z gospodarzem,<br />którego się nie zapomina",
        tiles=[
            ("Spójność", "Motyw przewodni eventu", "Robot-gospodarz spina wydarzenie klamrą: pojawia się na otwarciu, między punktami programu i na finale. Event zyskuje narrację, nie tylko agendę."),
            ("Energia", "Publiczność cały czas w grze", "Między wystąpieniami robot angażuje salę: zagadki, interakcje, mini-pokazy. Nie ma martwych przerw, jest ciągłe „co będzie dalej?”"),
            ("Bezpieczeństwo programu", "Operator czuwa nad timingiem", "Za robotem stoi nasz zespół: scenariusz, próby i operator na miejscu. Program idzie co do minuty."),
        ],
        scen_intro="Tak wygląda wydarzenie prowadzone z udziałem robota:",
        scens=[
            ("Otwarcie", "Robot wita uczestników i zapowiada, co wydarzy się w programie. Pierwszy punkt agendy jest jednocześnie pierwszym pokazem."),
            ("Prowadzenie bloków", "G1 zapowiada prelegentów i atrakcje, komentuje z humorem i płynnie łączy kolejne części wydarzenia."),
            ("Wielki finał", "Na zakończenie robot prowadzi finałowy pokaz choreografii i żegna gości — domknięcie, które zostaje w pamięci i na nagraniach."),
        ],
        faqs=[
            ("Czy robot poprowadzi event samodzielnie?", "Robot może samodzielnie poprowadzić wybrane punkty programu; przy pełnym prowadzeniu rekomendujemy duet z konferansjerem — robot daje widowisko, człowiek elastyczność. Oba warianty przygotowujemy scenariuszowo."),
            faq_price("do prowadzenia eventu"), faq_operator(), faq_book("do prowadzenia eventu"),
        ],
        blog_link=("blog-czy-robot-moze-prowadzic-event.html", "czy robot może prowadzić event?"),
        guides="ai", video="taniec",
        related_intro="Pokrewne role prowadzącego",
        related=[("robot-konferansjer.html", "Robot konferansjer"), ("robot-na-gale.html", "Robot na galę")],
    ),
    mk(
        slug="robot-witajacy-gosci", crumb="Robot witający gości",
        title="Robot witający gości — powitanie na evencie | 33bots",
        desc="Robot witający gości na wejściu: Unitree G1 wita uczestników gestem i głosem, robi pierwsze wrażenie i otwiera event z klasą →",
        keywords="robot witający gości, robot na powitanie, powitanie gości na evencie, robot przy wejściu, robot wita gości",
        eyebrow="Powitanie · Wejście · Pierwsze wrażenie",
        h1="Robot witający gości —<br />wejście robi różnicę.",
        sub="Pierwsze 30 sekund wydarzenia ustawia wszystko. Gdy gości wita robot humanoidalny — gestem, głosem, po imieniu, jeśli chcesz — każdy wchodzi do środka z telefonem w dłoni i uśmiechem na twarzy.",
        tiles_h2="Pierwsze wrażenie,<br />które niesie cały event",
        tiles=[
            ("Wejście", "Warta honorowa przyszłości", "Robot przy wejściu zamienia zwykłe „dzień dobry” w moment, który goście fotografują i wysyłają znajomym, zanim jeszcze zdejmą płaszcz."),
            ("Ton", "Zapowiedź czegoś większego", "Powitanie robotem komunikuje: to wydarzenie jest inne. Goście wchodzą z nastawieniem, że warto było przyjść — a to bezcenne dla całej agendy."),
            ("Płynność", "Zero korków przy wejściu", "Robot wita w ruchu ciągłym — gestem, głosem, krótką interakcją. Operator dba, by powitania nie blokowały wejścia nawet przy dużej frekwencji."),
        ],
        scen_intro="Powitanie robotem można skroić na wiele sposobów:",
        scens=[
            ("Klasyczne powitanie", "G1 stoi przy wejściu, wita gości gestem i głosem, zaprasza do środka. Prosty scenariusz o ogromnej sile rażenia."),
            ("Powitanie VIP", "Najważniejszych gości robot wita imiennie i odprowadza wzrokiem lub krokiem do strefy VIP — gest, który zapamiętuje każdy zarząd."),
            ("Welcome + strefa foto", "Zaraz za powitaniem robot zaprasza do wspólnego zdjęcia — goście wchodzą na salę już z pierwszym contentem w telefonie."),
        ],
        faqs=[
            ("Czy robot może witać gości po imieniu?", "Tak — przy evencie z listą gości robot może witać wybrane osoby imiennie. To szczególnie efektowne przy powitaniach VIP-ów i zarządu."),
            faq_price("do powitania gości"), faq_safe(), faq_transport(),
        ],
        blog_link=("blog-robot-recepcjonista-witajacy-gosci.html", "robot recepcjonista witający gości — poradnik"),
        video="powitanie",
        related_intro="Zobacz też pokrewne role",
        related=[("robot-recepcjonista.html", "Robot recepcjonista"), ("robot-na-bankiet.html", "Robot na bankiet")],
    ),
    mk(
        slug="robot-recepcjonista", crumb="Robot recepcjonista",
        title="Robot recepcjonista — obsługa gości i rejestracja | 33bots",
        desc="Robot recepcjonista na event, do hotelu lub biura: wita gości, odpowiada na pytania dzięki AI i kieruje do właściwych stref →",
        keywords="robot recepcjonista, robot na recepcję, robot obsługa gości, robot informacyjny, recepcja przyszłości",
        eyebrow="Recepcja · Informacja · Obsługa gości",
        h1="Robot recepcjonista —<br />recepcja, która robi wrażenie.",
        sub="Na evencie, w hotelowym lobby czy w biurowcu: robot recepcjonista wita gości, odpowiada na najczęstsze pytania dzięki AI i wskazuje drogę. Obsługa zostaje w rękach ludzi — pierwsze wrażenie przejmuje humanoid.",
        tiles_h2="Recepcja z humanoidem<br />w roli głównej",
        tiles=[
            ("Informacja", "Odpowiada na pytania", "Gdzie jest sala A? O której zaczyna się prelekcja? Robot odpowiada na powtarzalne pytania dzięki AI — a Twój zespół zajmuje się sprawami, które wymagają człowieka."),
            ("Rejestracja", "Wsparcie check-inu", "Robot wita uczestników przy rejestracji i skraca odczuwalny czas oczekiwania — kolejka z humanoidem to atrakcja, nie frustracja."),
            ("Wizerunek", "Lobby jak z przyszłości", "Recepcja z robotem to sygnał dla gości i klientów: ta firma naprawdę żyje technologią. Wrażenie zaczyna się przed pierwszym uściskiem dłoni."),
        ],
        scen_intro="Robot recepcjonista sprawdza się wszędzie, gdzie przybywają goście:",
        scens=[
            ("Recepcja eventowa", "Przy wejściu na konferencję czy galę robot wita uczestników, informuje o agendzie i kieruje do szatni, sal i stref."),
            ("Hotel i biurowiec", "W lobby robot wita gości i odpowiada na podstawowe pytania — atrakcja na dni otwarte, premiery i specjalne okazje."),
            ("Punkt informacyjny", "W galerii handlowej lub na uczelni robot pełni rolę mobilnego punktu informacji, który przyciąga zamiast czekać, aż ktoś podejdzie."),
        ],
        faqs=[
            ("Na jakie pytania odpowiada robot recepcjonista?", "Na te, które przygotujemy wspólnie: agenda, lokalizacje sal, informacje o firmie czy ofercie — plus pytania ogólne, z którymi radzi sobie AI. Operator czuwa nad przebiegiem interakcji."),
            faq_price("recepcjonista"), faq_operator(), faq_book("na recepcję wydarzenia"),
        ],
        blog_link=("blog-robot-recepcjonista-witajacy-gosci.html", "robot recepcjonista witający gości — poradnik"),
        guides="ai", video="powitanie",
        related_intro="Pokrewne zastosowania",
        related=[("robot-witajacy-gosci.html", "Robot witający gości"), ("robot-do-hotelu.html", "Robot do hotelu")],
    ),
    mk(
        slug="robot-tancerz", crumb="Robot tancerz",
        title="Robot tancerz — pokaz tańca robota na event | 33bots",
        desc="Robot tancerz: Unitree G1 wykonuje choreografie zsynchronizowane z muzyką. Pokaz tańca robota — hit każdego eventu i parkietu →",
        keywords="robot tancerz, taniec robota, pokaz tańca robota, tańczący robot, robot tańczy na evencie, choreografia robota",
        eyebrow="Taniec · Choreografia · Show",
        h1="Robot tancerz —<br />parkiet należy do niego.",
        sub="Ze wszystkich umiejętności G1 taniec robi największe wrażenie. Płynne, dynamiczne układy zsynchronizowane z muzyką — od show na scenie po wspólny taniec z gośćmi na parkiecie. To moment, w którym każdy sięga po telefon.",
        tiles_h2="Taniec, który<br />wiruje w sieci",
        tiles=[
            ("Choreografia", "Układy z prawdziwą dynamiką", "G1 tańczy całym ciałem: kroki, obroty, praca ramion i korpusu. To nie animacja — to fizyczny robot, który naprawdę tańczy przed publicznością."),
            ("Muzyka", "Utwór pod Twój event", "Choreografię synchronizujemy z muzyką dopasowaną do wydarzenia — od elektroniki na konferencji technologicznej po klasyki na weselnym parkiecie."),
            ("Viral", "Najczęściej nagrywany moment", "Taniec robota to statystycznie najmocniej udostępniany fragment każdej naszej realizacji. Jeden układ potrafi zebrać setki relacji."),
        ],
        scen_intro="Pokaz taneczny dopasowujemy do charakteru wydarzenia:",
        scens=[
            ("Show sceniczne", "Wyreżyserowany występ na scenie z pełnym układem choreograficznym — otwarcie gali, przerywnik konferencji albo finał wieczoru."),
            ("Taniec z gośćmi", "Robot dołącza do gości na parkiecie — wspólny taniec z humanoidem to atrakcja, która rozkręca każdą imprezę."),
            ("Bitwa taneczna", "Odważny wariant: goście kontra robot w przyjaznej bitwie tanecznej. Śmiech, doping i materiał wideo, który żyje tygodniami."),
        ],
        faqs=[
            ("Jakie tańce wykonuje robot?", "G1 ma repertuar dynamicznych układów choreograficznych synchronizowanych z muzyką — od energetycznych show po zabawne układy imprezowe. Repertuar stale rozszerzamy."),
            ("Czy robot zatańczy do naszej piosenki?", "W wielu przypadkach tak — daj nam znać z wyprzedzeniem, a sprawdzimy możliwość synchronizacji układu z wybranym utworem."),
            faq_price("tancerz"), faq_safe(),
        ],
        video="taniec",
        related_intro="Taniec robota świetnie działa na:",
        related=[("robot-na-wesele.html", "Wesele"), ("robot-na-impreze-firmowa.html", "Impreza firmowa"), ("show-robotow.html", "Show robotów")],
    ),
]

# ==================================================== MIEJSCA I BRANŻE

PLACES = [
    mk(
        slug="robot-do-centrum-handlowego", crumb="Robot do centrum handlowego",
        title="Robot do centrum handlowego — atrakcja i traffic | 33bots",
        desc="Robot humanoidalny do centrum handlowego: przyciąga odwiedzających, buduje traffic i angażuje klientów. Eventy, weekendy tematyczne, otwarcia →",
        keywords="robot do centrum handlowego, atrakcja do centrum handlowego, robot w centrum handlowym, event w centrum handlowym, traffic centrum handlowe",
        eyebrow="Retail · Traffic · Eventy w CH",
        h1="Robot do centrum handlowego —<br />traffic, który sam się nakręca.",
        sub="Centra handlowe walczą o odwiedzających — a nic nie ściąga rodzin z całego miasta tak, jak możliwość spotkania prawdziwego robota humanoidalnego. G1 buduje traffic, wydłuża czas wizyty i daje najemcom powód do radości.",
        tiles_h2="Atrakcja, która realnie<br />podnosi odwiedzalność",
        tiles=[
            ("Traffic", "Powód do wizyty w galerii", "„W ten weekend spotkasz u nas robota” — taka komunikacja działa na rodziny z dziećmi jak magnes. Odwiedzający przychodzą specjalnie na pokaz."),
            ("Czas wizyty", "Goście zostają dłużej", "Pokazy w blokach co godzinę–dwie sprawiają, że odwiedzający zostają na kolejny pokaz — a między nimi robią zakupy."),
            ("Social media", "Marketing robi się sam", "Setki zdjęć i rolek z oznaczeniem lokalizacji galerii to organiczny zasięg, którego nie da żadna kampania banerowa."),
        ],
        scen_intro="W przestrzeni centrum handlowego robot pracuje w sprawdzonym rytmie:",
        scens=[
            ("Pokazy cykliczne", "Kilka pokazów choreografii dziennie w wyznaczonej strefie — komunikowane wcześniej w social mediach galerii, budują falę odwiedzin na konkretne godziny."),
            ("Spacery po pasażu", "Między pokazami robot spaceruje po pasażu w asyście operatora — zatrzymuje przechodniów i prowadzi ich do strefy eventowej."),
            ("Strefa zdjęć", "Stały punkt ze zdjęciami i interakcjami: piątki, pozowanie, krótkie rozmowy z AI. Kolejka chętnych nie znika do końca dnia."),
        ],
        faqs=[
            ("Jak długo robot może pracować w galerii?", "Realizujemy zarówno pojedyncze dni eventowe, jak i całe weekendy. Robot pracuje w blokach pokazowych z przerwami technicznymi — harmonogram układamy pod godziny szczytu odwiedzin."),
            faq_price("do centrum handlowego"), faq_safe(), faq_transport(),
        ],
        video="spacer",
        related_intro="Podobne przestrzenie i scenariusze",
        related=[("robot-do-galerii-handlowej.html", "Robot do galerii handlowej"), ("robot-dla-sklepow.html", "Robot dla sklepów")],
    ),
    mk(
        slug="robot-do-galerii-handlowej", crumb="Robot do galerii handlowej",
        title="Robot do galerii handlowej — eventy i animacje | 33bots",
        desc="Robot humanoidalny do galerii handlowej: pokazy, animacje dla rodzin i strefa spotkań z robotem. Wsparcie marketingu galerii i najemców →",
        keywords="robot do galerii handlowej, atrakcja do galerii, event w galerii handlowej, animacje w galerii, robot dla galerii",
        eyebrow="Galerie handlowe · Animacje · Weekendy",
        h1="Robot do galerii handlowej —<br />weekend, na który się czeka.",
        sub="Kalendarz eventowy galerii potrzebuje mocnych punktów. Weekend z robotem humanoidalnym to gotowy format: pokazy taneczne, spotkania z robotem i strefa zdjęć, które ściągają rodziny i wypełniają pasaż.",
        tiles_h2="Gotowy format eventowy<br />dla Twojej galerii",
        tiles=[
            ("Format", "Event pod klucz", "Dostarczamy kompletny program: harmonogram pokazów, strefę interakcji, operatora i materiały do komunikacji. Marketing galerii dostaje gotowy produkt."),
            ("Rodziny", "Magnes na dzieci i rodziców", "Dzieci chcą zobaczyć robota, rodzice chcą zobaczyć miny dzieci. Efekt: rodzinne wizyty zaplanowane specjalnie pod wydarzenie."),
            ("Najemcy", "Wartość dla sklepów", "Pokazy można powiązać z aktywacjami najemców — robot zaprasza do konkretnych stref i wspiera akcje promocyjne sklepów."),
        ],
        scen_intro="Sprawdzony program weekendu z robotem w galerii:",
        scens=[
            ("Pokazy o pełnych godzinach", "Choreografia w strefie centralnej — komunikowana wcześniej, buduje regularne fale odwiedzających przez cały dzień."),
            ("Spotkania i zdjęcia", "Między pokazami robot wita odwiedzających, przybija piątki z dziećmi i pozuje do zdjęć na tle brandingu galerii."),
            ("Aktywacje z najemcami", "Robot może zapraszać do wybranych sklepów, wręczać kupony albo współprowadzić konkursy — łącząc atrakcję z celami sprzedażowymi."),
        ],
        faqs=[
            ("Czy robot jest bezpieczny wśród dzieci w galerii?", "Tak — operator przez cały czas kontroluje robota i dystans do najmłodszych, a G1 ma czujniki unikania przeszkód. Interakcje z dziećmi prowadzone są w wyznaczonej, nadzorowanej strefie."),
            faq_price("do galerii handlowej"), faq_operator(), faq_book("na weekend w galerii"),
        ],
        guides="dzieci", video="spacer",
        related_intro="Zobacz też",
        related=[("robot-do-centrum-handlowego.html", "Robot do centrum handlowego"), ("robot-dla-dzieci.html", "Robot dla dzieci")],
    ),
    mk(
        slug="robot-do-hotelu", crumb="Robot do hotelu",
        title="Robot do hotelu — atrakcja dla gości i eventów | 33bots",
        desc="Robot humanoidalny do hotelu: wita gości w lobby, uświetnia konferencje i bankiety, wyróżnia obiekt na tle konkurencji →",
        keywords="robot do hotelu, robot w hotelu, atrakcja hotelowa, robot w lobby, robot na konferencję w hotelu",
        eyebrow="Hotele · Lobby · Eventy hotelowe",
        h1="Robot do hotelu —<br />obiekt, o którym się mówi.",
        sub="Hotel konkuruje doświadczeniem — a żadne doświadczenie nie zapada w pamięć jak powitanie przez robota humanoidalnego. G1 pracuje w lobby, na hotelowych konferencjach i bankietach, dając obiektowi przewagę, którą goście fotografują.",
        tiles_h2="Przewaga, którą widać<br />od progu",
        tiles=[
            ("Lobby", "Powitanie z przyszłości", "Robot wita gości przy check-inie w wybrane dni lub przy specjalnych okazjach — pobyt zaczyna się od momentu WOW."),
            ("MICE", "Argument dla organizatorów", "Hotel, który oferuje pokaz robota jako opcję dla wydarzeń, wygrywa zapytania konferencyjne — to unikat w ofercie MICE."),
            ("PR", "Content dla marketingu obiektu", "Materiały z robotem w Waszych wnętrzach zasilają social media i OTA — wyróżnik, którego nie ma żaden konkurent w okolicy."),
        ],
        scen_intro="Robot w hotelu pracuje w kilku sprawdzonych scenariuszach:",
        scens=[
            ("Powitania w lobby", "W wybrane dni robot wita przyjeżdżających gości, pozuje do zdjęć i opowiada o hotelu dzięki AI — idealne przy otwarciach i jubileuszach obiektu."),
            ("Eventy w hotelu", "Konferencje, gale i wesela w Waszych salach zyskują atrakcję premium — pokaz robota jako punkt programu wydarzenia."),
            ("Pakiety specjalne", "Robot jako element ofert sezonowych: sylwester w hotelu, ferie z rodziną, walentynki — powód, by wybrać właśnie Wasz obiekt."),
        ],
        faqs=[
            ("Czy robot może występować w hotelu cyklicznie?", "Tak — poza pojedynczymi realizacjami oferujemy współpracę cykliczną, np. robot w lobby w każdy weekend miesiąca albo przy każdej dużej konferencji w obiekcie."),
            faq_price("do hotelu"), faq_operator(), faq_transport(),
        ],
        video="powitanie",
        related_intro="Scenariusze dla obiektów",
        related=[("robot-recepcjonista.html", "Robot recepcjonista"), ("robot-na-bankiet.html", "Robot na bankiet")],
    ),
    mk(
        slug="robot-do-restauracji", crumb="Robot do restauracji",
        title="Robot do restauracji — atrakcja dla gości lokalu | 33bots",
        desc="Robot humanoidalny do restauracji: wita gości, uświetnia otwarcia i wieczory tematyczne, przyciąga nowych klientów do lokalu →",
        keywords="robot do restauracji, robot w restauracji, atrakcja do restauracji, otwarcie restauracji atrakcja, robot w lokalu",
        eyebrow="Gastronomia · Otwarcia · Wieczory tematyczne",
        h1="Robot do restauracji —<br />stolik przy robocie poproszę.",
        sub="W gastronomii wygrywa ten, o kim się mówi. Wieczór z robotem humanoidalnym w Twoim lokalu to pełna sala, telefony nad stolikami i relacje z lokalizacją restauracji rozchodzące się po całym mieście.",
        tiles_h2="Pełna sala<br />i pełne social media",
        tiles=[
            ("Okazja", "Powód do rezerwacji", "„Wieczór z robotem” to gotowy pretekst do wizyty — goście rezerwują stoliki specjalnie na wydarzenie, także w słabsze dni tygodnia."),
            ("Doświadczenie", "Kolacja, którą się pamięta", "Robot wita gości, podchodzi do stolików i pozuje do zdjęć. Zwykła kolacja zmienia się w wydarzenie, o którym goście opowiadają tygodniami."),
            ("Lokalny szum", "Marketing szeptany na sterydach", "Relacje z oznaczeniem lokalu docierają do tysięcy osób w okolicy — najskuteczniejsza lokalna reklama, jaką można sobie wyobrazić."),
        ],
        scen_intro="Robot w restauracji sprawdza się przy kilku okazjach:",
        scens=[
            ("Otwarcie lokalu", "Na otwarciu robot wita pierwszych gości i prowadzi pokaz — start, który od razu ustawia lokal na mapie miasta."),
            ("Wieczory tematyczne", "Cykliczne „wieczory z robotem” budują stałą klientelę i wypełniają kalendarz rezerwacji w wybrane dni."),
            ("Eventy zamknięte", "Urodziny, spotkania firmowe i kolacje degustacyjne w Twoim lokalu zyskują atrakcję, która podnosi wartość całej oferty eventowej."),
        ],
        faqs=[
            ("Czy robot zmieści się w małym lokalu?", "G1 ma 130 cm wzrostu i poradzi sobie w większości przestrzeni restauracyjnych. Przed realizacją ustalamy plan sali, żeby dobrać bezpieczną trasę i strefę pokazów."),
            faq_price("do restauracji"), faq_safe(), faq_book("na wieczór w lokalu"),
        ],
        video="powitanie",
        related_intro="Podobne realizacje",
        related=[("robot-na-otwarcie.html", "Robot na otwarcie"), ("robot-do-hotelu.html", "Robot do hotelu")],
    ),
    mk(
        slug="robot-do-marketingu", crumb="Robot do marketingu",
        title="Robot do marketingu — kampanie i aktywacje z humanoidem | 33bots",
        desc="Robot humanoidalny do marketingu: aktywacje brandowe, kampanie, content wideo i ambient. Humanoid jako twarz Twojej akcji promocyjnej →",
        keywords="robot do marketingu, robot w kampanii, aktywacja marketingowa robot, robot w reklamie, marketing z robotem",
        eyebrow="Marketing · Aktywacje · Kampanie",
        h1="Robot do marketingu —<br />kampania, którą ludzie nagrywają.",
        sub="Największym wyzwaniem marketingu jest dziś uwaga. Robot humanoidalny ją gwarantuje: w aktywacji ulicznej, kampanii wideo czy akcji w punkcie sprzedaży G1 zatrzymuje ludzi i zamienia przechodniów w publiczność Twojej marki.",
        tiles_h2="Uwaga gwarantowana —<br />reszta to Twój przekaz",
        tiles=[
            ("Ambient", "Aktywacje, które niosą się same", "Robot z brandingiem marki w przestrzeni miejskiej lub punkcie sprzedaży to ambient, który dokumentują sami przechodnie — zasięg rośnie bez budżetu mediowego."),
            ("Wideo", "Content z humanoidem", "Spot, seria rolek czy kampania społecznościowa z robotem w roli głównej — format, który wyróżnia się w feedzie na pierwszy rzut oka."),
            ("Brand", "Robot jako ambasador", "G1 w barwach Twojej marki staje się jej fizycznym ambasadorem — spójnym, fotogenicznym i zawsze w formie."),
        ],
        scen_intro="Marketerzy wykorzystują robota na kilka sposobów:",
        scens=[
            ("Aktywacja brandowa", "Robot z logo marki pracuje w miejscu o dużym ruchu: rozdaje uwagę, zaprasza do interakcji i kieruje do Twojego punktu lub promocji."),
            ("Produkcja contentu", "Dzień zdjęciowy z robotem: materiały do kampanii, social mediów i e-commerce. Dostarczamy robota, operatora i choreografię pod scenariusz."),
            ("Launch i promocje", "Premiera produktu, otwarcie punktu, akcja rabatowa — robot nadaje akcji rozgłos i przyciąga media lokalne."),
        ],
        faqs=[
            ("Czy robot może występować w barwach naszej marki?", "Tak — branding robota i jego otoczenia to standardowa opcja: logo, kolory, elementy identyfikacji. Ustalamy szczegóły przy wycenie."),
            faq_price("do kampanii marketingowej"), faq_operator(), faq_transport(),
        ],
        blog_link=("blog-robotyka-w-marketingu.html", "robotyka w marketingu — przewodnik"),
        guides="marketing", video="branding",
        related_intro="Marketing z robotem w praktyce",
        related=[("robot-do-reklamy-i-filmu.html", "Robot do reklamy i filmu"), ("robot-na-premiere-produktu.html", "Robot na premierę")],
    ),
    mk(
        slug="robot-do-reklamy-i-filmu", crumb="Robot do reklamy i filmu",
        title="Robot do reklamy i filmu — humanoid na planie zdjęciowym | 33bots",
        desc="Robot humanoidalny do reklamy i filmu: wynajem Unitree G1 na plan zdjęciowy — spoty, filmy, produkcje TV. Z operatorem ruchu scenicznego →",
        keywords="robot do reklamy, robot do filmu, robot na plan zdjęciowy, humanoid w reklamie, wynajem robota do produkcji",
        eyebrow="Produkcja · Plan zdjęciowy · Spoty",
        h1="Robot do reklamy i filmu —<br />aktor, który nie gra.",
        sub="Prawdziwy humanoid w kadrze robi to, czego nie odda żadne CGI: jest fizyczny, wiarygodny i tańszy niż postprodukcja. Wynajmujemy G1 na plany reklam, filmów i produkcji TV — z operatorem, który realizuje wizję reżysera ujęcie po ujęciu.",
        tiles_h2="Prawdziwy robot<br />zamiast CGI",
        tiles=[
            ("Autentyzm", "Widz czuje różnicę", "Fizyczny robot w kadrze — z realnym światłem, cieniem i ruchem — buduje wiarygodność, której nie osiąga animacja. A widzowie coraz lepiej rozpoznają CGI."),
            ("Budżet", "Szybciej niż postprodukcja", "Ujęcia z prawdziwym robotem powstają na planie, nie w studiu 3D. Oszczędzasz tygodnie postprodukcji i związane z nią koszty."),
            ("Reżyseria", "Powtarzalność dubli", "Operator prowadzi robota według wskazówek reżysera — każdy dubel z tą samą precyzją ruchu, bez zmęczenia i humorów."),
        ],
        scen_intro="Na planie pracujemy jak każdy profesjonalny dział — z próbami, riderem i dyscypliną czasową:",
        scens=[
            ("Przygotowanie", "Przed zdjęciami omawiamy scenariusz i storyboard, dobieramy ruchy i choreografię robota pod ujęcia. Możliwa próba techniczna przed dniem zdjęciowym."),
            ("Dzień zdjęciowy", "Robot z operatorem pozostaje do dyspozycji planu: powtarzalne duble, korekty ruchu na bieżąco, współpraca z pionem operatorskim i oświetleniem."),
            ("Materiały dodatkowe", "Making-of z robotem to bonus, który produkcje uwielbiają — behind-the-scenes z humanoidem żyje w sieci równie mocno jak sam spot."),
        ],
        faqs=[
            ("Jakie ruchy robot wykona przed kamerą?", "Chód, gesty, taniec, interakcje z aktorami i rekwizytami — repertuar ruchów omawiamy na etapie przygotowań. Operator realizuje wskazówki reżysera na bieżąco między dublami."),
            ("Czy robot może grać z aktorami?", "Tak — G1 bezpiecznie pracuje w scenach z ludźmi. Sceny kontaktowe planujemy wcześniej i prowadzimy pod pełną kontrolą operatora."),
            faq_price("na plan zdjęciowy"), faq_transport(),
        ],
        video="gesty",
        related_intro="Produkcje z robotem",
        related=[("robot-do-teledysku.html", "Robot do teledysku"), ("robot-do-sesji-zdjeciowej.html", "Robot do sesji zdjęciowej")],
    ),
    mk(
        slug="robot-do-teledysku", crumb="Robot do teledysku",
        title="Robot do teledysku — humanoid w Twoim klipie | 33bots",
        desc="Robot humanoidalny do teledysku: Unitree G1 tańczy w klipie, gra sceny i daje materiał, który wyróżni Twój teledysk. Wynajem z operatorem →",
        keywords="robot do teledysku, robot w teledysku, humanoid w klipie, tańczący robot teledysk, robot do klipu muzycznego",
        eyebrow="Muzyka · Teledyski · Produkcja",
        h1="Robot do teledysku —<br />klip, który się wyróżni.",
        sub="Tańczący humanoid w teledysku to obraz, który zatrzymuje kciuk przy scrollowaniu. G1 tańczy do Twojego utworu, gra sceny z artystą i daje klipowi wizualny motyw, o którym będą pisać w komentarzach.",
        tiles_h2="Motyw wizualny,<br />który niesie klip",
        tiles=[
            ("Taniec", "Choreografia do Twojego bitu", "Układy robota synchronizujemy z utworem — od tanecznych sekwencji w rytmie po statyczne, klimatyczne kadry."),
            ("Duet", "Sceny z artystą", "Artysta i humanoid w jednym kadrze to mocny kontrast wizualny — duet, bitwa taneczna albo narracyjna rola robota w historii klipu."),
            ("Promocja", "Rozgłos wokół premiery", "„W klipie zagrał prawdziwy robot” to gotowy angle promocyjny — making-of i szorty z planu napędzają premierę utworu."),
        ],
        scen_intro="Współpracę przy teledysku prowadzimy jak każdą produkcję:",
        scens=[
            ("Koncept", "Omawiamy treatment klipu i rolę robota: choreografia, sceny fabularne, interakcje z artystą. Doradzamy, co zagra najlepiej w kadrze."),
            ("Plan zdjęciowy", "Robot z operatorem realizuje ujęcia według shot-listy — powtarzalne duble i korekty choreografii na bieżąco."),
            ("Content z planu", "Backstage z robotem to dodatkowy materiał promocyjny na social media artysty — często równie popularny jak sam klip."),
        ],
        faqs=[
            ("Czy robot zatańczy do naszego utworu?", "Tak — choreografię synchronizujemy z wybranym fragmentem utworu. Prześlij nam track z wyprzedzeniem, a przygotujemy układ pod tempo i charakter numeru."),
            faq_price("do teledysku"), faq_transport(), faq_book("na plan teledysku"),
        ],
        video="taniec",
        related_intro="Więcej o produkcjach",
        related=[("robot-do-reklamy-i-filmu.html", "Robot do reklamy i filmu"), ("robot-na-wystep-sceniczny.html", "Występ sceniczny robota")],
    ),
    mk(
        slug="robot-do-sesji-zdjeciowej", crumb="Robot do sesji zdjęciowej",
        title="Robot do sesji zdjęciowej — humanoid w Twoim kadrze | 33bots",
        desc="Robot humanoidalny do sesji zdjęciowej: kampanie, editoriale, lookbooki i content brandowy z Unitree G1. Wynajem z operatorem pozowania →",
        keywords="robot do sesji zdjęciowej, sesja z robotem, robot w sesji, humanoid do zdjęć, robot do kampanii zdjęciowej",
        eyebrow="Fotografia · Kampanie · Editoriale",
        h1="Robot do sesji zdjęciowej —<br />model, który nie mruga.",
        sub="Humanoid w kadrze natychmiast podnosi stawkę: kampania produktowa, editorial modowy czy sesja wizerunkowa z robotem wygląda jak z przyszłości. G1 pozuje, gestykuluje i trzyma pozy dokładnie tak, jak chce fotograf.",
        tiles_h2="Kadr, obok którego<br />nie da się przescrollować",
        tiles=[
            ("Pozy", "Pełna kontrola sylwetki", "Operator ustawia robota dokładnie według wizji fotografa: gesty, kąt głowy, dynamika sylwetki. Poza trzymana bez drżenia tak długo, jak trzeba."),
            ("Kontrast", "Człowiek × maszyna", "Zestawienie modeli z humanoidem daje kadry o mocnym napięciu wizualnym — ulubiony motyw editoriali i kampanii technologicznych marek."),
            ("Unikat", "Zdjęcia, których nikt nie ma", "Bank zdjęć stockowych nie zawiera Twojej marki z prawdziwym robotem. Po sesji masz materiał w 100% własny i w 100% wyróżnialny."),
        ],
        scen_intro="Sesja z robotem przebiega sprawnie, jeśli dobrze ją zaplanować:",
        scens=[
            ("Moodboard i plan", "Przed sesją omawiamy koncepcję i listę ujęć — doradzamy pozy i ruchy, które najlepiej wychodzą w fotografii."),
            ("Sesja", "Robot z operatorem do dyspozycji fotografa: zmiany póz na komendę, sekwencje ruchu do zdjęć dynamicznych, praca w studiu lub plenerze."),
            ("Wykorzystanie", "Materiały możesz wykorzystać w kampanii, na www i w social mediach — zakres licencji ustalamy prosto: zdjęcia są Twoje."),
        ],
        faqs=[
            ("Czy robot pracuje w studiu i w plenerze?", "Tak — G1 pracuje w obu środowiskach. W plenerze potrzebujemy równej nawierzchni i suchej pogody; szczegóły techniczne ustalamy przed sesją."),
            faq_price("na sesję zdjęciową"), faq_transport(), faq_book("na sesję"),
        ],
        video="gesty",
        related_intro="Pokrewne produkcje",
        related=[("robot-do-reklamy-i-filmu.html", "Robot do reklamy i filmu"), ("robot-do-marketingu.html", "Robot do marketingu")],
    ),
    mk(
        slug="robot-dla-dzieci", crumb="Robot dla dzieci",
        title="Robot dla dzieci — atrakcja na eventy dziecięce | 33bots",
        desc="Robot humanoidalny dla dzieci: pokazy, wspólny taniec i bezpieczne interakcje na dniach dziecka, piknikach i eventach rodzinnych →",
        keywords="robot dla dzieci, robot na event dla dzieci, atrakcja dla dzieci, robot na dzień dziecka, pokaz robota dla dzieci",
        eyebrow="Dzieci · Rodziny · Edukacja przez zabawę",
        h1="Robot dla dzieci —<br />bohater z bajki na żywo.",
        sub="Dla dorosłych robot to technologia. Dla dzieci — spełnienie marzenia: prawdziwy robot, który macha, tańczy i przybija piątki. Na eventach rodzinnych G1 wywołuje reakcje, których nie da żadna maskotka ani dmuchaniec.",
        tiles_h2="Atrakcja, przy której<br />dzieci zapominają o telefonach",
        tiles=[
            ("Emocje", "Oczy jak spodki", "Moment, w którym dziecko pierwszy raz widzi chodzącego robota, to czyste, niepodrabialne emocje — a rodzice nagrywają każdą sekundę."),
            ("Bezpieczeństwo", "Pod pełną kontrolą", "Operator prowadzi każdą interakcję i utrzymuje bezpieczny dystans. G1 ma czujniki przeszkód, a zasady kontaktu tłumaczymy dzieciom w formie zabawy."),
            ("Edukacja", "Technologia na żywo", "Pokaz robota to naturalna lekcja: skąd robot wie, jak chodzić? Czy myśli? Odpowiadamy na pytania dzieci, zamieniając zabawę w pierwszą lekcję robotyki."),
        ],
        scen_intro="Program dla najmłodszych ma swój sprawdzony rytm:",
        scens=[
            ("Pokaz z narracją", "Robot pokazuje, co potrafi — chód, taniec, gesty — a operator opowiada dzieciom, jak to działa. Interaktywnie, z pytaniami z widowni."),
            ("Wspólny taniec", "Dzieci tańczą razem z robotem — najprostsza i najskuteczniejsza zabawa, jaka istnieje. Śmiech gwarantowany, nagrania rodziców też."),
            ("Piątki i zdjęcia", "Każde dziecko może przybić piątkę i zrobić zdjęcie z robotem — pamiątka, którą będzie pokazywać w szkole przez tydzień."),
        ],
        faqs=[
            ("Od jakiego wieku dzieci mogą uczestniczyć w pokazie?", "Pokaz oglądać mogą dzieci w każdym wieku. Bezpośrednie interakcje (piątki, zdjęcia) prowadzimy z dziećmi pod opieką dorosłych, zawsze pod kontrolą operatora."),
            faq_price("na event dla dzieci"), faq_safe(), faq_transport(),
        ],
        blog_link=("blog-robot-na-event-dla-dzieci.html", "robot na evencie dla dzieci — poradnik"),
        guides="dzieci", video="gesty",
        related_intro="Eventy z myślą o najmłodszych",
        related=[("robot-na-dzien-dziecka.html", "Robot na Dzień Dziecka"), ("robot-na-piknik-firmowy.html", "Robot na piknik firmowy")],
    ),
    mk(
        slug="robot-dla-sklepow", crumb="Robot dla sklepów",
        title="Robot dla sklepów — traffic i promocje w retail | 33bots",
        desc="Robot humanoidalny dla sklepów: otwarcia, promocje i akcje specjalne. Humanoid przyciąga klientów do Twojego punktu sprzedaży →",
        keywords="robot dla sklepów, robot do sklepu, atrakcja na otwarcie sklepu, robot w punkcie sprzedaży, robot retail",
        eyebrow="Retail · Otwarcia · Akcje promocyjne",
        h1="Robot dla sklepów —<br />klienci przyjdą zobaczyć.",
        sub="Otwarcie, promocja, rocznica sklepu — każda akcja retailowa potrzebuje ruchu. Robot humanoidalny przed wejściem lub w sali sprzedaży ściąga przechodniów skuteczniej niż megafon i hostessy razem wzięte.",
        tiles_h2="Ruch w sklepie,<br />który widać w kasie",
        tiles=[
            ("Wejścia", "Przechodzień staje się klientem", "Robot przy witrynie zatrzymuje ruch pieszy — a operator i komunikacja kierują zaciekawionych prosto do środka, na promocję lub degustację."),
            ("Okazja", "Rozgłos wokół akcji", "Akcja promocyjna z robotem żyje w lokalnych mediach i społecznościach — sklep zyskuje rozpoznawalność daleko poza swoją ulicą."),
            ("Sieci", "Format do powielenia", "Dla sieci handlowych przygotowujemy roadshow: robot odwiedza kolejne lokalizacje, a każda wizyta to lokalny event z gotową komunikacją."),
        ],
        scen_intro="W retailu robot pracuje na konkretny wynik:",
        scens=[
            ("Otwarcie sklepu", "Robot wita pierwszych klientów, przecina wstęgę z obsadą i prowadzi pokaz — otwarcie, o którym mówi cała okolica."),
            ("Akcja promocyjna", "G1 zaprasza do skorzystania z promocji, wręcza kupony i kieruje do stref wyprzedażowych — zabawa, która sprzedaje."),
            ("Roadshow po lokalizacjach", "Cykl wizyt robota w kolejnych sklepach sieci — każda lokalizacja dostaje swój dzień z eventem i contentem."),
        ],
        faqs=[
            ("Czy robot może pracować przed sklepem, na zewnątrz?", "Tak — przy sprzyjającej pogodzie i równej nawierzchni robot może pracować przed wejściem. Wariant wewnętrzny działa niezależnie od aury; oba omawiamy przy wycenie."),
            faq_price("do sklepu"), faq_operator(), faq_book("na akcję w sklepie"),
        ],
        blog_link=("blog-robot-na-otwarcie-sklepu.html", "robot na otwarcie sklepu — case i poradnik"),
        guides="marketing", video="branding",
        related_intro="Retail z robotem",
        related=[("robot-na-otwarcie.html", "Robot na otwarcie"), ("robot-dla-franczyzy.html", "Robot dla franczyzy")],
    ),
    mk(
        slug="robot-dla-franczyzy", crumb="Robot dla franczyzy",
        title="Robot dla franczyzy — eventy sieci i konwenty | 33bots",
        desc="Robot humanoidalny dla sieci franczyzowych: konwenty franczyzobiorców, otwarcia nowych punktów i roadshow po lokalizacjach →",
        keywords="robot dla franczyzy, robot na konwent franczyzy, atrakcja na otwarcie punktu, event sieci franczyzowej, roadshow franczyza",
        eyebrow="Franczyza · Sieci · Roadshow",
        h1="Robot dla franczyzy —<br />jedna atrakcja, cała sieć.",
        sub="Sieć franczyzowa żyje z powtarzalności — i z momentów, które ją przełamują. Robot humanoidalny obsłuży konwent franczyzobiorców, otwarcia kolejnych punktów i ogólnopolski roadshow marki, wszędzie z tym samym efektem WOW.",
        tiles_h2="Atrakcja skalowalna<br />jak Twoja sieć",
        tiles=[
            ("Konwenty", "Gwóźdź programu zjazdu", "Na konwencie franczyzobiorców robot otwiera galę, prezentuje wyniki sieci albo po prostu kradnie show — zjazd, który partnerzy zapamiętają."),
            ("Otwarcia", "Każdy nowy punkt z hukiem", "Powtarzalny format otwarcia z robotem: pokaz, zdjęcia, lokalny szum. Nowy franczyzobiorca dostaje start, jakiego nie ma konkurencja."),
            ("Spójność", "Ten sam standard w każdym mieście", "Od Szczecina po Rzeszów — ta sama ekipa, ten sam scenariusz, ten sam efekt. Marka mówi jednym głosem w całej Polsce."),
        ],
        scen_intro="Dla sieci franczyzowych pracujemy w trzech formatach:",
        scens=[
            ("Konwent i gala sieci", "Robot współprowadzi galę, wręcza wyróżnienia najlepszym partnerom i prowadzi pokaz finałowy — mocny akcent największego wydarzenia sieci w roku."),
            ("Otwarcia punktów", "Sprawdzony scenariusz otwarcia powtarzamy w każdej nowej lokalizacji — franczyzobiorca dostaje event pod klucz w dniu startu."),
            ("Roadshow marki", "Zaplanowana trasa robota po lokalizacjach sieci: każda wizyta to lokalny event, materiały do social mediów i wzrost ruchu w punkcie."),
        ],
        faqs=[
            ("Czy oferujecie stałe warunki dla sieci?", "Tak — przy cyklicznej współpracy (otwarcia, roadshow) przygotowujemy ofertę ramową ze stałymi warunkami dla wszystkich lokalizacji sieci."),
            faq_price("dla sieci franczyzowej"), faq_transport(), faq_operator(),
        ],
        video="branding",
        related_intro="Formaty dla sieci",
        related=[("robot-na-konwent.html", "Robot na konwent"), ("robot-na-roadshow.html", "Robot na roadshow"), ("robot-dla-sklepow.html", "Robot dla sklepów")],
    ),
    mk(
        slug="robot-na-uczelnie", crumb="Robot na uczelnię",
        title="Robot na uczelnię — dni otwarte, juwenalia, konferencje | 33bots",
        desc="Robot humanoidalny na uczelnię: dni otwarte, juwenalia, konferencje naukowe i promocja kierunków technicznych. Pokaz z Unitree G1 →",
        keywords="robot na uczelnię, robot na dni otwarte uczelni, robot na juwenalia, pokaz robota na uczelni, robot na konferencję naukową",
        eyebrow="Uczelnie · Dni otwarte · Juwenalia",
        h1="Robot na uczelnię —<br />rekrutacja przez fascynację.",
        sub="Kandydaci wybierają uczelnie, które robią wrażenie. Pokaz prawdziwego humanoida na dniach otwartych, juwenaliach czy pikniku naukowym pokazuje, że Wasza uczelnia jest tam, gdzie dzieje się przyszłość — i zostaje w relacjach kandydatów na długo.",
        tiles_h2="Uczelnia, na którą<br />chce się aplikować",
        tiles=[
            ("Rekrutacja", "Dni otwarte z frekwencją", "Robot na dniach otwartych przyciąga kandydatów i ich rodziców do stoisk wydziałów — a rozmowa o rekrutacji zaczyna się sama."),
            ("Nauka", "Pokaz z wartością merytoryczną", "Pokaz łączymy z opowieścią o robotyce, AI i inżynierii — studenci i kandydaci widzą technologię, o której czytają w sylabusach."),
            ("Juwenalia", "Gwiazda miasteczka", "Na juwenaliach i piknikach naukowych robot ściąga tłumy — a uczelnia zyskuje content, który żyje w studenckich social mediach."),
        ],
        scen_intro="Na uczelniach robot występuje w kilku rolach:",
        scens=[
            ("Dni otwarte", "Robot wita kandydatów, prowadzi pokazy o wyznaczonych godzinach i pozuje do zdjęć — najmocniejszy punkt programu rekrutacyjnego."),
            ("Wykład z demonstracją", "Pokaz możliwości G1 połączony z prelekcją o współczesnej robotyce — dla studentów, kół naukowych i szkół partnerskich."),
            ("Eventy studenckie", "Juwenalia, otrzęsiny, gale wydziałowe — robot dodaje wydarzeniom rozmachu i daje samorządom frekwencyjny hit."),
        ],
        faqs=[
            ("Czy pokaz ma wartość edukacyjną?", "Tak — na życzenie łączymy pokaz z częścią merytoryczną: jak działa lokomocja dwunożna, jak robot utrzymuje równowagę, jak łączy się z AI. Poziom dostosowujemy do odbiorców."),
            faq_price("na uczelnię"), faq_safe(), faq_book("na dni otwarte"),
        ],
        blog_link=("blog-robot-na-juwenalia-festiwal.html", "robot na juwenaliach i festiwalach"),
        video="spacer",
        related_intro="Wydarzenia akademickie i edukacyjne",
        related=[("robot-na-event-edukacyjny.html", "Event edukacyjny"), ("robot-na-dzien-otwarty.html", "Dzień otwarty")],
    ),
]

from seo_pages_content2 import EXTRA_PAGES

ALL_PAGES = SERVICES + ROLES + PLACES + EXTRA_PAGES
